# Generated by Django 3.2 on 2021-05-14 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Caracterentidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Caracter de la entidad')),
            ],
            options={
                'verbose_name': 'Caracter de la entidad',
                'verbose_name_plural': 'Caracter de la entidad',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del país')),
                ('phone_code', models.CharField(max_length=5, verbose_name='Código número telefónico')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de Discapacidad')),
            ],
            options={
                'verbose_name': 'TIpo de Discapacidad',
                'verbose_name_plural': 'TIpo de Discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Formacion')),
            ],
            options={
                'verbose_name': 'Formacion',
                'verbose_name_plural': 'Formacion',
            },
        ),
        migrations.CreateModel(
            name='FormacionE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Formacion de la entidad')),
            ],
            options={
                'verbose_name': 'Formacion Entidad',
                'verbose_name_plural': 'Formacion Entidad',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de Identidad de Genero')),
            ],
            options={
                'verbose_name': 'Tipo de Identidad de  Genero',
                'verbose_name_plural': 'TIpo de Identidad de Generos',
            },
        ),
        migrations.CreateModel(
            name='GroupEtnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de grupo etnico')),
            ],
            options={
                'verbose_name': 'TIpo de grupo etnico',
                'verbose_name_plural': 'TIpo de grupo etnicos',
            },
        ),
        migrations.CreateModel(
            name='HealthRegimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Regimen de salud')),
            ],
            options={
                'verbose_name': 'Regimen de salud',
                'verbose_name_plural': 'Regimenes de salud',
            },
        ),
        migrations.CreateModel(
            name='HeritageWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Vigia de Patrimonio')),
            ],
            options={
                'verbose_name': 'Vigia de patrimonio',
                'verbose_name_plural': 'Vigias de patrimonio',
            },
        ),
        migrations.CreateModel(
            name='HousingStratum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Estrato de vivienda')),
            ],
            options={
                'verbose_name': 'Estrato de vivienda',
                'verbose_name_plural': 'Estratos de vivienda',
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Manifestacion')),
            ],
            options={
                'verbose_name': 'Manifestacion',
                'verbose_name_plural': 'Manifestacion',
            },
        ),
        migrations.CreateModel(
            name='MonthlyIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Ingresos Mensuales')),
            ],
            options={
                'verbose_name': 'Ingreso Mensual',
                'verbose_name_plural': 'Ingresos Mensuales',
            },
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de Naturaleza')),
            ],
            options={
                'verbose_name': 'Naturaleza',
                'verbose_name_plural': 'Naturaleza',
            },
        ),
        migrations.CreateModel(
            name='NivelEntidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Niveles')),
            ],
            options={
                'verbose_name': 'Nivel de entidad',
                'verbose_name_plural': 'Niveles de entidad',
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(blank=True, max_length=30, verbose_name='Ocupacion')),
            ],
            options={
                'verbose_name': 'Ocupacion',
                'verbose_name_plural': 'Ocupaciones',
            },
        ),
        migrations.CreateModel(
            name='PensionRegimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Regimen de pension')),
            ],
            options={
                'verbose_name': 'Regimen de pension',
                'verbose_name_plural': 'Regimenes de pension',
            },
        ),
        migrations.CreateModel(
            name='PopulationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de Grupo poblacional')),
            ],
            options={
                'verbose_name': 'TIpo de Grupo poblacional',
                'verbose_name_plural': 'TIpo de Grupo poblacional',
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de Regimen')),
            ],
            options={
                'verbose_name': 'Regimen',
                'verbose_name_plural': 'Regimen',
            },
        ),
        migrations.CreateModel(
            name='RuralZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Zona rural')),
            ],
            options={
                'verbose_name': 'Zona rural',
                'verbose_name_plural': 'Zonas rurales',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Subregimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Subregimen')),
            ],
            options={
                'verbose_name': 'Subregimen',
                'verbose_name_plural': 'Subregimen',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'TIpo de documentos',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='COmuna')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agentcultural.city', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del departamento')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agentcultural.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre Entidad')),
                ('sigla', models.CharField(blank=True, max_length=254, null=True, verbose_name='Sigla')),
                ('nit', models.CharField(blank=True, max_length=10, null=True, verbose_name='NIt')),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='Año de constitución')),
                ('reseña', models.TextField(blank=True, null=True, verbose_name='Reseña')),
                ('nombre_representante', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre Representante legal')),
                ('apellidos_representante', models.CharField(blank=True, max_length=254, null=True, verbose_name='Apellidos Representante legal')),
                ('identification', models.IntegerField(blank=True, max_length=30, null=True, verbose_name='Número de identificación')),
                ('lugar_expedicion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Lugar de expendición')),
                ('nombre_contacto', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre de contacto')),
                ('apellidos_contacto', models.CharField(blank=True, max_length=254, null=True, verbose_name='Apellidos del contacto')),
                ('cargo', models.CharField(blank=True, max_length=254, null=True, verbose_name='Cargo')),
                ('vinculacion', models.DateField(auto_now=True, null=True, verbose_name='Año de vinculación')),
                ('zona', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Zona(rural-urbana)')),
                ('direccion', models.CharField(blank=True, max_length=254, null=True, verbose_name='Direccion')),
                ('correspondencia', models.CharField(blank=True, max_length=254, null=True, verbose_name='Direccion de correspondencia')),
                ('phone_movil', models.CharField(blank=True, max_length=30, null=True, verbose_name='telefono movil')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='telefono')),
                ('apartado_aereo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apartado aereo')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('pagina_web', models.CharField(blank=True, max_length=30, null=True, verbose_name='Pagina Web')),
                ('practica', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DANZA - CONTEMPORANEA', 'DANZA - CONTEMPORANEA'), ('DANZA - BALLET', 'DANZA - BALLET'), ('DANZA - URBANA', 'DANZA - URBANA'), ('DANZA - FOLCLOR', 'DANZA - FOLCLOR'), ('MÚSICA - BANDAS', 'MÚSICA - BANDAS'), ('MÚSICA - COROS', 'MÚSICA - COROS'), ('MÚSICA - ORQUESTA SINFÓNICA', 'MÚSICA - ORQUESTA SINFÓNICA'), ('MÚSICA - AGRUPACIONES MÚSICA TRADICIONAL', 'MÚSICA - AGRUPACIONES MÚSICA TRADICIONAL'), ('MÚSICA - POPULAR', 'MÚSICA - POPULAR'), ('MÚSICA - AGRUPACIONES MÚSICA ACADÉMICA', 'MÚSICA - AGRUPACIONES MÚSICA ACADÉMICA'), ('TEATRO - DE SALA', 'TEATRO - DE SALA'), ('TEATRO - TITERES', 'TEATRO - TITERES'), ('TEATRO - MUSICAL', 'TEATRO - MUSICAL'), ('TEATRO - PARA ESPACIOS NO CONVENCIONALES', 'TEATRO - PARA ESPACIOS NO CONVENCIONALES'), ('LITERATURA - EDITORIALES', 'LITERATURA - EDITORIALES'), ('LITERATURA - REVISTAS', 'LITERATURA - REVISTAS'), ('LITERATURA - TALLERES', 'LITERATURA - TALLERES'), ('LITERATURA - INSTITUCIONES LITERARIAS', 'LITERATURA - INSTITUCIONES LITERARIAS'), ('TEATRO - UNIVERSIDADES', 'TEATRO - UNIVERSIDADES'), ('TEATRO - CÀMARA DEL LIBRO', 'TEATRO - CÀMARA DEL LIBRO'), ('ARTES - PLÁSTICA', 'ARTES - PLÁSTICA'), ('ARTES - VISUAL', 'ARTES - VISUAL'), ('CINEMATOGRAFÍA', 'CINEMATOGRAFÍA')], max_length=82, null=True, verbose_name='PRACTICA:')),
                ('tipo_produccion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PRODUCCIÓN, COMERCIALIZACIÓN Y DIVULGACIÓN', 'PRODUCCIÓN, COMERCIALIZACIÓN Y DIVULGACIÓN'), ('EMPRESA FONOGRÁFICA', 'EMPRESA FONOGRÁFICA'), ('EDITORIAL', 'EDITORIAL'), ('EMPRESA EN CONSTRUCCIÓN Y REPARACIÓN DE INSTITUCIÓN', 'EMPRESA EN CONSTRUCCIÓN Y REPARACIÓN DE INSTITUCIÓN'), ('PRODUCTORA DE EVENTOS', 'PRODUCTORA DE EVENTOS'), ('REPRESENTACIÓN ARTÍSTICA', 'REPRESENTACIÓN ARTÍSTICA'), ('DISTRIBUIDORA', 'DISTRIBUIDORA'), ('GALERISTA', 'GALERISTA')], max_length=82, null=True, verbose_name='Producción, Comercialización Y Divulgación: ')),
                ('personeria', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Tiene personería jurídica?')),
                ('dependencia', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Depende de alguna entidad')),
                ('entidad_dependiente', models.CharField(blank=True, max_length=30, verbose_name='Nombre de la entidad')),
                ('nivel', models.CharField(blank=True, choices=[('INTERNACIONAL', 'INTERNACIONAL'), ('NACIONAL', 'NACIONAL'), ('DEPARTAMENTAL', 'DEPARTAMENTAL'), ('MUNICIPAL', 'MUNICIPAL')], max_length=22, null=True, verbose_name=' Nivel de la entidad')),
                ('red', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='La entidad pertenece alguna red?')),
                ('name_red', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de la red')),
                ('nivel_red', models.CharField(blank=True, choices=[('INTERNACIONAL', 'INTERNACIONAL'), ('NACIONAL', 'NACIONAL'), ('DEPARTAMENTAL', 'DEPARTAMENTAL'), ('MUNICIPAL', 'MUNICIPAL')], max_length=22, null=True, verbose_name='Nivel de la red')),
                ('acceso_internet', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Tiene la organización acceso a internet?')),
                ('espacio', models.CharField(blank=True, choices=[('PROPIO', 'PROPIO'), ('EN ARRIENDO', 'EN ARRIENDO'), ('EN COMODATO', 'EN COMODATO'), ('PRESTAMO', 'PRESTAMO'), ('NO TIENE', 'NO TIENE')], max_length=22, null=True, verbose_name='Espacio')),
                ('infraestructura_discapacitados', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Cuenta la entidad con infraestructura para discapacitados?')),
                ('interes_cultural', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Ocupa la entidad un bien de interés cultural?')),
                ('nivel_interescultural', models.CharField(blank=True, choices=[('INTERNACIONAL', 'INTERNACIONAL'), ('NACIONAL', 'NACIONAL'), ('DEPARTAMENTAL', 'DEPARTAMENTAL'), ('MUNICIPAL', 'MUNICIPAL')], max_length=22, null=True, verbose_name='Nivel del bien de interes cultural que ocupa?')),
                ('espacios_actividades', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AUDITORIOS', 'AUDITORIOS'), ('AULAS', 'AULAS'), ('BIBLIOTECAS', 'BIBLIOTECAS'), ('CENTROS DE DOCUMENTACIÓN', 'CENTROS DE DOCUMENTACIÓN'), ('ESTUDIOS DE PRODUCCIÓN', 'ESTUDIOS DE PRODUCCIÓN'), ('GALERÍAS', 'GALERÍAS'), ('MUSEOS', 'MUSEOS'), ('OFICINAS', 'OFICINAS'), ('PUNTOS DE VENTA', 'PUNTOS DE VENTA'), ('SALAS DE ENSAYO', 'SALAS DE ENSAYO'), ('SALAS DE ESTUDIO INDIVIDUAL', 'SALAS DE ESTUDIO INDIVIDUAL'), ('SALAS DE EXHIBICIÓN', 'SALAS DE EXHIBICIÓN'), ('SALAS DE REUNIÓN', 'SALAS DE REUNIÓN'), ('TALLERES', 'TALLERES'), ('TEATROS', 'TEATROS')], max_length=29, null=True, verbose_name='Espacio disponibles por la organización para el desarrollo de sus actividades')),
                ('genero_empleo', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=22, null=True, verbose_name='Su organización generó empleo directo el último año?')),
                ('tipo_empleo', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=22, null=True, verbose_name='Que tipo de empleo directo generó?')),
                ('cantidad_noremunerado', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='Cuántos empleos no remunerados generó?')),
                ('duracion_noremunerados', models.CharField(blank=True, choices=[('1 - 4 MESES', 'INTERNACIONAL'), ('5 - 8 MESES', 'NACIONAL'), ('MAS DE 8 MESES', 'DEPARTAMENTAL')], max_length=22, null=True, verbose_name='Qué duración tuvieron los empleos no remunerados que generó?')),
                ('cantidad_remunerado', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='Cuántos empleos remunerados generó?')),
                ('duracion_remunerados', models.CharField(blank=True, choices=[('1 - 4 MESES', 'INTERNACIONAL'), ('5 - 8 MESES', 'NACIONAL'), ('MAS DE 8 MESES', 'DEPARTAMENTAL')], max_length=22, null=True, verbose_name='Qué duración tuvieron los empleos remunerados que generó?')),
                ('cantidadremunerado_ops', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='Cuántos empleos remunerados generó por contratos de servicios?')),
                ('cantidadremunerado_laboral', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='Cuántos empleos remunerados generó por contrato laboral?')),
                ('cantidadrecurso_humano', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='Cantidad de recurso humano con el que cuenta la entidad?')),
                ('actividad_principal', models.CharField(blank=True, choices=[('FORMACIÓN', 'FORMACIÓN'), ('PRÁCTICA ARTISTICA', 'PRÁCTICA ARTISTICA'), ('GESTIÓN', 'GESTIÓN'), ('CIRCULACIÓN Y COMERCIALIZACIÓN', 'CIRCULACIÓN Y COMERCIALIZACIÓN')], max_length=42, null=True, verbose_name=' EL CAMPO DE LA PRINCIPAL ACTIVIDAD ARTÍSTICA O CULTURAL QUE DESARROLLA LA ORGANIZACIÓN ES')),
                ('otra_actividad', models.CharField(blank=True, choices=[('FORMACIÓN', 'FORMACIÓN'), ('PRÁCTICA ARTISTICA', 'PRÁCTICA ARTISTICA'), ('GESTIÓN', 'GESTIÓN'), ('CIRCULACIÓN Y COMERCIALIZACIÓN', 'CIRCULACIÓN Y COMERCIALIZACIÓN')], max_length=42, null=True, verbose_name='OTROS CAMPOS DE ACTIVIDADES EN QUE TRABAJA LA ORGANIZACIÓN SON:')),
                ('area_artistica', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Artes Visuales', 'Artes Visuales'), ('Cine y audiovisuales', 'Cine y audiovisuales'), ('Circo', 'Circo'), ('Danza', 'Danza'), ('Literatura y editorial', 'Literatura y editorial'), ('Musica ', 'Musica '), ('Teatro', 'Teatro'), ('Bibiliotecas', 'Bibiliotecas'), ('Bibliotecas patrimoniales', 'Bibliotecas patrimoniales'), ('Audiovisual', 'Audiovisual'), ('Editorial', 'Editorial'), ('Fonográfica', 'Fonográfica'), ('Museos ', 'Museos '), ('Museos patrimoniales', 'Museos patrimoniales'), ('Actos festivos y lúdicos', 'Actos festivos y lúdicos'), ('Conocimientos tradicionales sobre la naturaleza y el universo', 'Conocimientos tradicionales sobre la naturaleza y el universo'), ('Conocimientos y técnicas tradicionales asociadas al hábitat', 'Conocimientos y técnicas tradicionales asociadas al hábitat'), ('Cultura culinaria', 'Cultura culinaria'), ('Eventos religiosos tradicionales de carácter colectivo', 'Eventos religiosos tradicionales de carácter colectivo'), ('Juegos y deportes tradicionales', 'Juegos y deportes tradicionales'), ('Lenguas, lenguajes y tradicion oral', 'Lenguas, lenguajes y tradicion oral'), ('Medicina tradicional', 'Medicina tradicional'), ('PCI asociado a espacios culturales', 'PCI asociado a espacios culturales'), ('PCI asociado a los evenos de la vida cotidiana', 'PCI asociado a los evenos de la vida cotidiana'), ('Produccion tradicional y propia', 'Produccion tradicional y propia'), ('Sistemas normativos y formas de organizacion social tradicionales', 'Sistemas normativos y formas de organizacion social tradicionales'), ('Técnicas y tradicionales asociadas a la fabricación de objetos artesanales', 'Técnicas y tradicionales asociadas a la fabricación de objetos artesanales'), ('Museos patrimoniales', 'Museos patrimoniales')], max_length=82, null=True, verbose_name='EL ÁREA ARTÍSTICA EN LA QUE LA ORGANIZACIÓN DESARROLLA SU PRINCIPAL ACTIVIDAD ES:')),
                ('numero_obras', models.IntegerField(blank=True, max_length=80, null=True, verbose_name='¿NÚMERO DE OBRAS PRODUCIDAS DURANTE EL ÚLTIMO AÑO, COMO EL RESULTADO DE LA PRÁCTICA ARTÍSTICA QUE DESARROLLA LAORGANIZACIÓN?')),
                ('practicas', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿LAS PRÁCTICAS ASTÍSTICAS QUE REALIZA LA ORGANIZACIÓN INCLUYEN ACTIVIDADES DE FORMACIÓN DE PÚBLICOS? ')),
                ('acceso', models.CharField(blank=True, choices=[('GRATUITO Y PÚBLICO', 'GRATUITO Y PÚBLICO'), ('GRATUITO RESTRINGIDO', 'GRATUITO RESTRINGIDO'), ('PAGO', 'PAGO'), ('APORTE', 'APORTE'), ('VOLUNTARIO', 'VOLUNTARIO'), ('OTRO', 'OTRO')], max_length=22, null=True, verbose_name=' EL ACCESO DEL PÚBLICO AL RESULTADO DE LA PRÁCTICA ARTÍSTICA QUE DESARROLLA LA ORGANIZACIÓN ES DE CARÁCTER ')),
                ('proyectos', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name=' ¿LA ENTIDAD ORGANIZA REGULARMENTE PROGRAMAS O PROYECTOS ENFOCADOS ESPECÍFICAMENTE A ATENDER NIÑOS , JO¿ÓVENES, ADULTOS O PERSONAS MAYORES?')),
                ('grupos_edad', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INFANCIA', 'INFANCIA'), ('JUVENTUD', 'JUVENTUD'), ('ADULTOS', 'ADULTOS'), ('TERCERA EDAD', 'TERCERA EDAD'), ('TODOS', 'TODOS')], max_length=22, null=True, verbose_name='¿HACIA CUÁLES GRUPOS DE EDAD SE ENFOCAN ESOS PROGRAMAS O PROYECTOS?')),
                ('grupos_poblacion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INFANCIA', 'INFANCIA'), ('JUVENTUD', 'JUVENTUD'), ('ADULTOS', 'ADULTOS'), ('TERCERA EDAD', 'TERCERA EDAD'), ('TODOS', 'TODOS')], max_length=22, null=True, verbose_name='¿A QUE GRUPO PERTENECE LA POBLACIÓN BENEFICIARÍA DE LA PRODUCCIÓN ARTISTÍCA Y CULTURAL DE LA ORGANIZACIÓN?')),
                ('organizacion_actividades', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿DESARROLLA LA ORGANIZACIÓN ACTIVIDADES ESPECÍFICAMENTE DIRIGIDAS A PERSONAS CON DISCAPACIDAD?')),
                ('personas_discapacidad', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿DESARROLLA LA ORGANIZACIÓN ACTIVIDADES ESPECÍFICAMENTE DIRIGIDAS A PERSONAS CON DISCAPACIDAD?')),
                ('imparte_formacion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Artes Visuales', 'Artes Visuales'), ('Cine y audiovisuales', 'Cine y audiovisuales'), ('Circo', 'Circo'), ('Danza', 'Danza'), ('Literatura y editorial', 'Literatura y editorial'), ('Musica ', 'Musica '), ('Teatro', 'Teatro'), ('Bibiliotecas', 'Bibiliotecas'), ('Bibliotecas patrimoniales', 'Bibliotecas patrimoniales'), ('Audiovisual', 'Audiovisual'), ('Editorial', 'Editorial'), ('Fonográfica', 'Fonográfica'), ('Museos ', 'Museos '), ('Museos patrimoniales', 'Museos patrimoniales'), ('Actos festivos y lúdicos', 'Actos festivos y lúdicos'), ('Conocimientos tradicionales sobre la naturaleza y el universo', 'Conocimientos tradicionales sobre la naturaleza y el universo'), ('Conocimientos y técnicas tradicionales asociadas al hábitat', 'Conocimientos y técnicas tradicionales asociadas al hábitat'), ('Cultura culinaria', 'Cultura culinaria'), ('Eventos religiosos tradicionales de carácter colectivo', 'Eventos religiosos tradicionales de carácter colectivo'), ('Juegos y deportes tradicionales', 'Juegos y deportes tradicionales'), ('Lenguas, lenguajes y tradicion oral', 'Lenguas, lenguajes y tradicion oral'), ('Medicina tradicional', 'Medicina tradicional'), ('PCI asociado a espacios culturales', 'PCI asociado a espacios culturales'), ('PCI asociado a los evenos de la vida cotidiana', 'PCI asociado a los evenos de la vida cotidiana'), ('Produccion tradicional y propia', 'Produccion tradicional y propia'), ('Sistemas normativos y formas de organizacion social tradicionales', 'Sistemas normativos y formas de organizacion social tradicionales'), ('Técnicas y tradicionales asociadas a la fabricación de objetos artesanales', 'Técnicas y tradicionales asociadas a la fabricación de objetos artesanales'), ('Museos patrimoniales', 'Museos patrimoniales')], max_length=82, null=True, verbose_name=' ¿AREAS ARTÍSTICAS EN LAS QUE IMPARTE FORMACIÓN?')),
                ('modalidad', models.CharField(blank=True, choices=[('FORMAL', 'FORMAL'), ('NO FORMAL', 'NO FORMAL')], max_length=82, null=True, verbose_name='  PRINCIPAL MODALIDAD DE FORMACIÓN QUE IMPARTE LA ORGANIZACIÓN')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('caracter_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.caracterentidad', verbose_name='Caracter de la entidad')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.city', verbose_name='Municipio')),
                ('etnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.groupetnico', verbose_name='¿HACÍA CUALES MINORÍAS ÉTNICAS SE ENFOCAN ESTOS PROGRAMAS O PROYECTOS?')),
                ('formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agentcultural.formacione', verbose_name='Formación')),
                ('naturaleza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.naturaleza', verbose_name='Naturaleza')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.regimen', verbose_name='Tipo de Regimen')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.region', verbose_name='Departamento')),
                ('subregimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.subregimen', verbose_name='Tipo de Subregimen')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.typedocument', verbose_name='TIpode documento')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrador de la entidad')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.zone', verbose_name='Centro poblado')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agentcultural.region', verbose_name='Departamento'),
        ),
        migrations.CreateModel(
            name='AgentCultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(blank=True, max_length=30, null=True, verbose_name='Número de identificación')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Primer Nombre')),
                ('other_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Otros Nombres')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Primer apellido')),
                ('last_name2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo apellido')),
                ('artistic_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre artistico')),
                ('birthday', models.DateField(auto_now=True, null=True, verbose_name='Fecha de nacimiento')),
                ('rut', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='RUT')),
                ('code_rut', models.CharField(blank=True, max_length=30, verbose_name='RUT')),
                ('adress', models.CharField(blank=True, max_length=30, verbose_name='Direccion')),
                ('zona', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Zona(rural-urbana)')),
                ('beps', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Tiene BEPS?')),
                ('phone_movil', models.CharField(blank=True, max_length=30, null=True, verbose_name='telefono movil')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('sector', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Artes', 'Artes'), ('Bibliotecas', 'Bibliotecas'), ('Industrias Culturales', 'Industrias Culturales'), ('Museos', 'Museos'), ('Patrimonio cultural inmaterial', 'Patrimonio cultural inmaterial'), ('Patrimonio cultural inmueble', 'Patrimonio cultural inmueble'), ('Patrimonio cultural mueble', 'Patrimonio cultural mueble')], max_length=133, null=True, verbose_name='Sector')),
                ('area2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Artes Visuales', 'Artes Visuales'), ('Cine y audiovisuales', 'Cine y audiovisuales'), ('Circo', 'Circo'), ('Danza', 'Danza'), ('Literatura y editorial', 'Literatura y editorial'), ('Musica ', 'Musica '), ('Teatro', 'Teatro'), ('Bibiliotecas', 'Bibiliotecas'), ('Bibliotecas patrimoniales', 'Bibliotecas patrimoniales'), ('Audiovisual', 'Audiovisual'), ('Editorial', 'Editorial'), ('Fonográfica', 'Fonográfica'), ('Museos ', 'Museos '), ('Museos patrimoniales', 'Museos patrimoniales'), ('Actos festivos y lúdicos', 'Actos festivos y lúdicos'), ('Conocimientos tradicionales sobre la naturaleza y el universo', 'Conocimientos tradicionales sobre la naturaleza y el universo'), ('Conocimientos y técnicas tradicionales asociadas al hábitat', 'Conocimientos y técnicas tradicionales asociadas al hábitat'), ('Cultura culinaria', 'Cultura culinaria'), ('Eventos religiosos tradicionales de carácter colectivo', 'Eventos religiosos tradicionales de carácter colectivo'), ('Juegos y deportes tradicionales', 'Juegos y deportes tradicionales'), ('Lenguas, lenguajes y tradicion oral', 'Lenguas, lenguajes y tradicion oral'), ('Medicina tradicional', 'Medicina tradicional'), ('PCI asociado a espacios culturales', 'PCI asociado a espacios culturales'), ('PCI asociado a los evenos de la vida cotidiana', 'PCI asociado a los evenos de la vida cotidiana'), ('Produccion tradicional y propia', 'Produccion tradicional y propia'), ('Sistemas normativos y formas de organizacion social tradicionales', 'Sistemas normativos y formas de organizacion social tradicionales'), ('Técnicas y tradicionales asociadas a la fabricación de objetos artesanales', 'Técnicas y tradicionales asociadas a la fabricación de objetos artesanales'), ('Museos patrimoniales', 'Museos patrimoniales')], max_length=772, null=True, verbose_name='Area')),
                ('vigia_patrimonio', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Vigia patrimonio')),
                ('portador_manifestacion', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Portador de manifestacion patrimonio')),
                ('mas_formacion', models.TextField(blank=True, max_length=500, verbose_name='Describa si tiene mas formacion en un texto')),
                ('experiencia', models.TextField(blank=True, max_length=2000, verbose_name='Describa su experiencia')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.activity', verbose_name='Activity')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.city', verbose_name='Municipio')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agentcultural.country', verbose_name='País')),
                ('disability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.disability', verbose_name='Discapacidad')),
                ('etnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.groupetnico', verbose_name='Grupo etnico')),
                ('formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.formacion', verbose_name='Formacion')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.genero', verbose_name='Genero')),
                ('health_regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.healthregimen', verbose_name='Regimen de salud')),
                ('housing_stratum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.housingstratum', verbose_name='Estrato vivienda')),
                ('manifestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.manifestation', verbose_name='Manifestacion')),
                ('monthly_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.monthlyincome', verbose_name='Ingresos mensuales')),
                ('pension_regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.pensionregimen', verbose_name='Regimen de pension')),
                ('population_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.populationgroup', verbose_name='Grupo poblacional')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.region', verbose_name='Departamento')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.typedocument', verbose_name='TIpode documento')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.zone', verbose_name='Centro poblado')),
            ],
            options={
                'verbose_name': 'Agente cultural',
                'verbose_name_plural': 'Agente Cultural',
            },
        ),
    ]
