# Generated by Django 3.2 on 2021-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0002_auto_20210514_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/images/', verbose_name='Imagen del agente'),
        ),
    ]
