# Generated by Django 3.2 on 2021-05-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0003_alter_agentcultural_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='formacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.formacione', verbose_name='Formación'),
        ),
    ]
