# Generated by Django 3.2 on 2021-08-23 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Caracterentidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Caracter de la entidad')),
            ],
            options={
                'verbose_name': 'Caracter de la entidad',
                'verbose_name_plural': 'Caracter de la entidad',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del país')),
                ('phone_code', models.CharField(max_length=5, verbose_name='Código número telefónico')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='TIpo de Discapacidad')),
            ],
            options={
                'verbose_name': 'TIpo de Discapacidad',
                'verbose_name_plural': 'TIpo de Discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Formacion')),
            ],
            options={
                'verbose_name': 'Formacion',
                'verbose_name_plural': 'Formacion',
            },
        ),
        migrations.CreateModel(
            name='FormacionE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Formacion de la entidad')),
            ],
            options={
                'verbose_name': 'Formacion Entidad',
                'verbose_name_plural': 'Formacion Entidad',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de Identidad de Genero')),
            ],
            options={
                'verbose_name': 'Tipo de Identidad de  Genero',
                'verbose_name_plural': 'TIpo de Identidad de Generos',
            },
        ),
        migrations.CreateModel(
            name='GroupEtnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de grupo etnico')),
            ],
            options={
                'verbose_name': 'TIpo de grupo etnico',
                'verbose_name_plural': 'TIpo de grupo etnicos',
            },
        ),
        migrations.CreateModel(
            name='HealthRegimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Regimen de salud')),
            ],
            options={
                'verbose_name': 'Regimen de salud',
                'verbose_name_plural': 'Regimenes de salud',
            },
        ),
        migrations.CreateModel(
            name='HeritageWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Vigia de Patrimonio')),
            ],
            options={
                'verbose_name': 'Vigia de patrimonio',
                'verbose_name_plural': 'Vigias de patrimonio',
            },
        ),
        migrations.CreateModel(
            name='HousingStratum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Estrato de vivienda')),
            ],
            options={
                'verbose_name': 'Estrato de vivienda',
                'verbose_name_plural': 'Estratos de vivienda',
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Manifestacion')),
            ],
            options={
                'verbose_name': 'Manifestacion',
                'verbose_name_plural': 'Manifestacion',
            },
        ),
        migrations.CreateModel(
            name='MonthlyIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Ingresos Mensuales')),
            ],
            options={
                'verbose_name': 'Ingreso Mensual',
                'verbose_name_plural': 'Ingresos Mensuales',
            },
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de Naturaleza')),
            ],
            options={
                'verbose_name': 'Naturaleza',
                'verbose_name_plural': 'Naturaleza',
            },
        ),
        migrations.CreateModel(
            name='NivelEntidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Niveles')),
            ],
            options={
                'verbose_name': 'Nivel de entidad',
                'verbose_name_plural': 'Niveles de entidad',
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(blank=True, max_length=30, verbose_name='Ocupacion')),
            ],
            options={
                'verbose_name': 'Ocupacion',
                'verbose_name_plural': 'Ocupaciones',
            },
        ),
        migrations.CreateModel(
            name='PensionRegimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Regimen de pension')),
            ],
            options={
                'verbose_name': 'Regimen de pension',
                'verbose_name_plural': 'Regimenes de pension',
            },
        ),
        migrations.CreateModel(
            name='PopulationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de Grupo poblacional')),
            ],
            options={
                'verbose_name': 'TIpo de Grupo poblacional',
                'verbose_name_plural': 'TIpo de Grupo poblacional',
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='TIpo de Regimen')),
            ],
            options={
                'verbose_name': 'Regimen',
                'verbose_name_plural': 'Regimen',
            },
        ),
        migrations.CreateModel(
            name='RuralZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Zona rural')),
            ],
            options={
                'verbose_name': 'Zona rural',
                'verbose_name_plural': 'Zonas rurales',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Subregimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Subregimen')),
            ],
            options={
                'verbose_name': 'Subregimen',
                'verbose_name_plural': 'Subregimen',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'TIpo de documentos',
            },
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='HÉCHO VICTIMIZANTE')),
            ],
            options={
                'verbose_name': 'Hecho victimizante',
                'verbose_name_plural': 'Hechos victimizantes',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='COmuna')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agentcultural.city', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del departamento')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agentcultural.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='1.1. NOMBRE:')),
                ('sigla', models.CharField(blank=True, max_length=254, null=True, verbose_name='1.2. SIGLA:')),
                ('nit', models.CharField(blank=True, max_length=10, null=True, verbose_name='1.3. NIT:')),
                ('date', models.DateField(blank=True, null=True, verbose_name='1.4. AÑO DE CONSTITUCIÓN')),
                ('reseña', models.TextField(blank=True, null=True, verbose_name='1.5. RESEÑA')),
                ('nombre_representante', models.CharField(blank=True, max_length=254, null=True, verbose_name='1.6. NOMBRES DEL REPRESENTANTE LEGAL: ')),
                ('apellidos_representante', models.CharField(blank=True, max_length=254, null=True, verbose_name='1.7. APELLIDOS DEL REPRESENTANTE LEGAL')),
                ('cargo_representante', models.CharField(blank=True, max_length=254, null=True, verbose_name='1.8. CARGO DEL REPRESENTANTE')),
                ('vinculacion_representante', models.DateField(blank=True, null=True, verbose_name='1.9. AÑO DE VINCULACIÓN')),
                ('identification', models.IntegerField(blank=True, max_length=30, null=True, verbose_name='1.11. NÚMERO DE DOCUMENTO')),
                ('lugar_expedicion', models.CharField(blank=True, max_length=10, null=True, verbose_name='1.12. LUGAR DE EXPEDICIÓN:')),
                ('nombre_contacto', models.CharField(blank=True, max_length=254, null=True, verbose_name='1.13. NOMBRES DEL CONTACTO:')),
                ('apellidos_contacto', models.CharField(blank=True, max_length=254, null=True, verbose_name='1.14. APELLIDOS DEL CONTACTO:')),
                ('cargo', models.CharField(blank=True, max_length=254, null=True, verbose_name='1.15. CARGO DEL CONTACTO:')),
                ('vinculacion', models.DateField(auto_now=True, null=True, verbose_name='1.16. AÑO DE VINCULACIÓN:')),
                ('zona', models.CharField(blank=True, choices=[('URBANA', 'URBANA'), ('RURAL', 'RURAL')], max_length=10, null=True, verbose_name='2.2. ÁREA')),
                ('direccion', models.CharField(blank=True, max_length=254, null=True, verbose_name='2.3. DIRECCIÓN')),
                ('correspondencia', models.CharField(blank=True, max_length=254, null=True, verbose_name='2.4. DIRECCIÓN CORRESPONDENCIA:')),
                ('phone_movil', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.5. TELEFONO:')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.6. FAX')),
                ('apartado_aereo', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.7. APARTADO AÉREO')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='2.8. E-MAIL:')),
                ('pagina_web', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.9. PÁGINA WEB:')),
                ('practica', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DANZA - CONTEMPORANEA', 'DANZA - CONTEMPORANEA'), ('DANZA - BALLET', 'DANZA - BALLET'), ('DANZA - URBANA', 'DANZA - URBANA'), ('DANZA - FOLCLOR', 'DANZA - FOLCLOR'), ('MÚSICA - BANDAS', 'MÚSICA - BANDAS'), ('MÚSICA - COROS', 'MÚSICA - COROS'), ('MÚSICA - ORQUESTA SINFÓNICA', 'MÚSICA - ORQUESTA SINFÓNICA'), ('MÚSICA - AGRUPACIONES MÚSICA TRADICIONAL', 'MÚSICA - AGRUPACIONES MÚSICA TRADICIONAL'), ('MÚSICA - POPULAR', 'MÚSICA - POPULAR'), ('MÚSICA - AGRUPACIONES MÚSICA ACADÉMICA', 'MÚSICA - AGRUPACIONES MÚSICA ACADÉMICA'), ('TEATRO - DE SALA', 'TEATRO - DE SALA'), ('TEATRO - TITERES', 'TEATRO - TITERES'), ('TEATRO - MUSICAL', 'TEATRO - MUSICAL'), ('TEATRO - PARA ESPACIOS NO CONVENCIONALES', 'TEATRO - PARA ESPACIOS NO CONVENCIONALES'), ('LITERATURA - EDITORIALES', 'LITERATURA - EDITORIALES'), ('LITERATURA - REVISTAS', 'LITERATURA - REVISTAS'), ('LITERATURA - TALLERES', 'LITERATURA - TALLERES'), ('LITERATURA - INSTITUCIONES LITERARIAS', 'LITERATURA - INSTITUCIONES LITERARIAS'), ('TEATRO - UNIVERSIDADES', 'TEATRO - UNIVERSIDADES'), ('TEATRO - CÀMARA DEL LIBRO', 'TEATRO - CÀMARA DEL LIBRO'), ('ARTES - PLÁSTICA', 'ARTES - PLÁSTICA'), ('ARTES - VISUAL', 'ARTES - VISUAL'), ('CINEMATOGRAFÍA', 'CINEMATOGRAFÍA')], max_length=82, null=True, verbose_name='3.1. PRÁCTICA ARTÍSTICA:')),
                ('tipo_produccion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PRODUCCIÓN, COMERCIALIZACIÓN Y DIVULGACIÓN', 'PRODUCCIÓN, COMERCIALIZACIÓN Y DIVULGACIÓN'), ('EMPRESA FONOGRÁFICA', 'EMPRESA FONOGRÁFICA'), ('EDITORIAL', 'EDITORIAL'), ('EMPRESA EN CONSTRUCCIÓN Y REPARACIÓN DE INSTITUCIÓN', 'EMPRESA EN CONSTRUCCIÓN Y REPARACIÓN DE INSTITUCIÓN'), ('PRODUCTORA DE EVENTOS', 'PRODUCTORA DE EVENTOS'), ('REPRESENTACIÓN ARTÍSTICA', 'REPRESENTACIÓN ARTÍSTICA'), ('DISTRIBUIDORA', 'DISTRIBUIDORA'), ('GALERISTA', 'GALERISTA')], max_length=82, null=True, verbose_name='3.3. PRODUCCIÓN, COMERCIALIZACIÓN Y DIVULGACIÓN: ')),
                ('personeria', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.4. TIENE PERSONERÍA JURÍDICA:')),
                ('objeto_social', models.TextField(blank=True, max_length=2000, verbose_name='3.7. OBJETO SOCIAL')),
                ('dependencia', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.10. DEPENDE DE ALGUNA ENTIDAD:')),
                ('entidad_dependiente', models.CharField(blank=True, max_length=30, verbose_name='3.11. NOMBRE DE LA ENTIDAD:')),
                ('nivel', models.CharField(blank=True, choices=[('INTERNACIONAL', 'INTERNACIONAL'), ('NACIONAL', 'NACIONAL'), ('DEPARTAMENTAL', 'DEPARTAMENTAL'), ('MUNICIPAL', 'MUNICIPAL')], max_length=22, null=True, verbose_name=' 3.12. NIVEL:')),
                ('red', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.13. LA ENTIDAD PERTENECE A ALGUNA RED?:')),
                ('name_red', models.CharField(blank=True, max_length=30, null=True, verbose_name='3.14. NOMBRE DE LA RED:')),
                ('nivel_red', models.CharField(blank=True, choices=[('INTERNACIONAL', 'INTERNACIONAL'), ('NACIONAL', 'NACIONAL'), ('DEPARTAMENTAL', 'DEPARTAMENTAL'), ('MUNICIPAL', 'MUNICIPAL')], max_length=22, null=True, verbose_name='3.15. NIVEL:')),
                ('acceso_internet', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.1. ¿TIENE LA ORGANIZACIÓN ACCESOS A INTERNET?')),
                ('espacio', models.CharField(blank=True, choices=[('PROPIO', 'PROPIO'), ('EN ARRIENDO', 'EN ARRIENDO'), ('EN COMODATO', 'EN COMODATO'), ('PRESTAMO', 'PRESTAMO'), ('NO TIENE', 'NO TIENE')], max_length=22, null=True, verbose_name='4.2. ESPACIO')),
                ('infraestructura_discapacitados', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.3. CUENTA LA ENTIDAD CON INFRAESTRUCTURA PARA DISCAPACITADOS:')),
                ('interes_cultural', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.4. OCUPA LA ENTIDAD UN BIEN DE INTERÉS CULTURAL:')),
                ('nivel_interescultural', models.CharField(blank=True, choices=[('INTERNACIONAL', 'INTERNACIONAL'), ('NACIONAL', 'NACIONAL'), ('DEPARTAMENTAL', 'DEPARTAMENTAL'), ('MUNICIPAL', 'MUNICIPAL')], max_length=22, null=True, verbose_name='4.5. ¿NIVEL DEL BIEN DE INTERES CULTURAL QUE OCUPA?')),
                ('espacios_actividades', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AUDITORIOS', 'AUDITORIOS'), ('AULAS', 'AULAS'), ('BIBLIOTECAS', 'BIBLIOTECAS'), ('CENTROS DE DOCUMENTACIÓN', 'CENTROS DE DOCUMENTACIÓN'), ('ESTUDIOS DE PRODUCCIÓN', 'ESTUDIOS DE PRODUCCIÓN'), ('GALERÍAS', 'GALERÍAS'), ('MUSEOS', 'MUSEOS'), ('OFICINAS', 'OFICINAS'), ('PUNTOS DE VENTA', 'PUNTOS DE VENTA'), ('SALAS DE ENSAYO', 'SALAS DE ENSAYO'), ('SALAS DE ESTUDIO INDIVIDUAL', 'SALAS DE ESTUDIO INDIVIDUAL'), ('SALAS DE EXHIBICIÓN', 'SALAS DE EXHIBICIÓN'), ('SALAS DE REUNIÓN', 'SALAS DE REUNIÓN'), ('TALLERES', 'TALLERES'), ('TEATROS', 'TEATROS')], max_length=29, null=True, verbose_name='4.6. ESPACIOS DISPONIBLES POR LA ORGANIZACIÓN PARA EL DESARROLLO DE SUS ACTIVIDADES')),
                ('genero_empleo', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=22, null=True, verbose_name='5.1. ¿SU ORGANIZACIÓN GENERÓ EMPLEO DIRECTO EL ÚLTIMO AÑO?:')),
                ('tipo_empleo', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=22, null=True, verbose_name='5.2. ¿QUÉ TIPO DE EMPLEO DIRECTO GENERÓ?:')),
                ('cantidad_noremunerado', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.3. ¿CUÁNTOS EMPLEOS NO REMUNERADOS GENERÓ?:')),
                ('duracion_noremunerados', models.CharField(blank=True, choices=[('1 - 4 MESES', 'INTERNACIONAL'), ('5 - 8 MESES', 'NACIONAL'), ('MAS DE 8 MESES', 'DEPARTAMENTAL')], max_length=22, null=True, verbose_name='5.4. ¿QUÉ DURACIÓN TUVIERON LOS EMPLEOS NO REMUNERADOS QUE GENERÓ?:')),
                ('cantidad_remunerado', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.5. ¿CUÁNTOS EMPLEOS REMUNERADOS GENERÓ?:')),
                ('duracion_remunerados', models.CharField(blank=True, choices=[('1 - 4 MESES', 'INTERNACIONAL'), ('5 - 8 MESES', 'NACIONAL'), ('MAS DE 8 MESES', 'DEPARTAMENTAL')], max_length=22, null=True, verbose_name='5.6. ¿QUÉ DURACIÓN TUVIERON LOS EMPLEOS REMUNERADOS QUE GENERÓ?:')),
                ('cantidadremunerado_ops', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.7. ¿CUÁNTOS EMPLEOS REMUNERADOS GENERÓ POR CONTRATOS DE SERVICIOS?:')),
                ('cantidadremunerado_laboral', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.8. ¿CUÁNTOS EMPLEOS REMUNERADOS GENERÓ POR CONTRATO LABORAL?:')),
                ('cantidadrecurso_humano', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.9. ¿CANTIDAD DE RECURSO HUMANO CON EL QUE CUENTA LA ENTIDAD?:')),
                ('actividad_principal', models.CharField(blank=True, choices=[('FORMACIÓN', 'FORMACIÓN'), ('PRÁCTICA ARTISTICA', 'PRÁCTICA ARTISTICA'), ('GESTIÓN', 'GESTIÓN'), ('CIRCULACIÓN Y COMERCIALIZACIÓN', 'CIRCULACIÓN Y COMERCIALIZACIÓN')], max_length=42, null=True, verbose_name='6.1. EL CAMPO DE LA PRINCIPAL ACTIVIDAD ARTÍSTICA O CULTURAL QUE DESARROLLA LA ORGANIZACIÓN ES')),
                ('otra_actividad', models.CharField(blank=True, choices=[('FORMACIÓN', 'FORMACIÓN'), ('PRÁCTICA ARTISTICA', 'PRÁCTICA ARTISTICA'), ('GESTIÓN', 'GESTIÓN'), ('CIRCULACIÓN Y COMERCIALIZACIÓN', 'CIRCULACIÓN Y COMERCIALIZACIÓN')], max_length=42, null=True, verbose_name='6.2. OTROS CAMPOS DE ACTIVIDADES EN QUE TRABAJA LA ORGANIZACIÓN SON:')),
                ('area_artistica', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Artes Visuales', 'Artes Visuales'), ('Cine y audiovisuales', 'Cine y audiovisuales'), ('Circo', 'Circo'), ('Danza', 'Danza'), ('Literatura y editorial', 'Literatura y editorial'), ('Música ', 'Música '), ('Teatro', 'Teatro'), ('Bibliotecas', 'Bibliotecas'), ('Bibliotecas patrimoniales', 'Bibliotecas patrimoniales'), ('Audiovisual', 'Audiovisual'), ('Editorial', 'Editorial'), ('Fonográfica', 'Fonográfica'), ('Museos ', 'Museos '), ('Museos patrimoniales', 'Museos patrimoniales'), ('Actos festivos y lúdicos', 'Actos festivos y lúdicos'), ('Conocimientos tradicionales sobre la naturaleza y el universo', 'Conocimientos tradicionales sobre la naturaleza y el universo'), ('Conocimientos y técnicas tradicionales asociadas al hábitat', 'Conocimientos y técnicas tradicionales asociadas al hábitat'), ('Cultura culinaria', 'Cultura culinaria'), ('Eventos religiosos tradicionales de carácter colectivo', 'Eventos religiosos tradicionales de carácter colectivo'), ('Juegos y deportes tradicionales', 'Juegos y deportes tradicionales'), ('Lenguas, lenguajes y tradición oral', 'Lenguas, lenguajes y tradición oral'), ('Medicina tradicional', 'Medicina tradicional'), ('PCI asociado a espacios culturales', 'PCI asociado a espacios culturales'), ('PCI asociado a los eventos de la vida cotidiana', 'PCI asociado a los eventos de la vida cotidiana'), ('Producción tradicional y propia', 'Producción tradicional y propia'), ('Sistemas normativos y formas de organización social tradicionales', 'Sistemas normativos y formas de organización social tradicionales'), ('Técnicas y tradicionales asociadas a la fabricación de objetos artesanales', 'Técnicas y tradicionales asociadas a la fabricación de objetos artesanales'), ('Museos patrimoniales', 'Museos patrimoniales')], max_length=82, null=True, verbose_name='6.3. EL ÁREA ARTÍSTICA EN LA QUE LA ORGANIZACIÓN DESARROLLA SU PRINCIPAL ACTIVIDAD ES:')),
                ('numero_obras', models.IntegerField(blank=True, max_length=80, null=True, verbose_name='6.4. ¿NÚMERO DE OBRAS PRODUCIDAS DURANTE EL ÚLTIMO AÑO, COMO EL RESULTADO DE LA PRÁCTICA ARTÍSTICA QUE DESARROLLA LA ORGANIZACIÓN?')),
                ('practicas', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='6.5. ¿LAS PRÁCTICAS ASTÍSTICAS QUE REALIZA LA ORGANIZACIÓN INCLUYEN ACTIVIDADES DE FORMACIÓN DE PÚBLICOS? ')),
                ('ultimo_año', models.CharField(blank=True, choices=[('GRATUITO Y PÚBLICO', 'GRATUITO Y PÚBLICO'), ('GRATUITO RESTRINGIDO', 'GRATUITO RESTRINGIDO'), ('PAGO', 'PAGO'), ('APORTE', 'APORTE'), ('VOLUNTARIO', 'VOLUNTARIO'), ('OTRO', 'OTRO')], max_length=22, null=True, verbose_name=' 6.6. DURANTE EL ÚLTIMO AÑO EL PROMEDIO MENSUAL APROXIMADO DE PERSONAS (PÚBLICO) QUE ASISTIERON A LA ACTIVIDAD ARTÍSTICA O CULTURAL DE LA ORGANIZACIÓ FUE: ')),
                ('acceso', models.CharField(blank=True, choices=[('GRATUITO Y PÚBLICO', 'GRATUITO Y PÚBLICO'), ('GRATUITO RESTRINGIDO', 'GRATUITO RESTRINGIDO'), ('PAGO', 'PAGO'), ('APORTE', 'APORTE'), ('VOLUNTARIO', 'VOLUNTARIO'), ('OTRO', 'OTRO')], max_length=22, null=True, verbose_name=' 6.7. EL ACCESO DEL PÚBLICO AL RESULTADO DE LA PRÁCTICA ARTÍSTICA QUE DESARROLLA LA ORGANIZACIÓN ES DE CARÁCTER ')),
                ('proyectos', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name=' 6.8. ¿LA ENTIDAD ORGANIZA REGULARMENTE PROGRAMAS O PROYECTOS ENFOCADOS ESPECÍFICAMENTE A ATENDER NIÑOS , JÓVENES, ADULTOS O PERSONAS MAYORES?')),
                ('grupos_edad', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INFANCIA', 'INFANCIA'), ('JUVENTUD', 'JUVENTUD'), ('ADULTOS', 'ADULTOS'), ('TERCERA EDAD', 'TERCERA EDAD'), ('TODOS', 'TODOS')], max_length=22, null=True, verbose_name='6.9. ¿HACIA CUÁLES GRUPOS DE EDAD SE ENFOCAN ESOS PROGRAMAS O PROYECTOS?')),
                ('grupos_poblacion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INFANCIA', 'INFANCIA'), ('JUVENTUD', 'JUVENTUD'), ('ADULTOS', 'ADULTOS'), ('TERCERA EDAD', 'TERCERA EDAD'), ('TODOS', 'TODOS')], max_length=22, null=True, verbose_name='6.10. ¿A QUE GRUPO PERTENECE LA POBLACIÓN BENEFICIARÍA DE LA PRODUCCIÓN ARTISTÍCA Y CULTURAL DE LA ORGANIZACIÓN?')),
                ('organizacion_actividades', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='6.11. ¿DESARROLLA LA ORGANIZACIÓN ACTIVIDADES DIRIGIDAS A MINORÍAS ÉTNICAS?')),
                ('personas_discapacidad', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='6.13. ¿DESARROLLA LA ORGANIZACIÓN ACTIVIDADES ESPECÍFICAMENTE DIRIGIDAS A PERSONAS CON DISCAPACIDAD?')),
                ('imparte_formacion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Artes Visuales', 'Artes Visuales'), ('Cine y audiovisuales', 'Cine y audiovisuales'), ('Circo', 'Circo'), ('Danza', 'Danza'), ('Literatura y editorial', 'Literatura y editorial'), ('Música ', 'Música '), ('Teatro', 'Teatro'), ('Bibliotecas', 'Bibliotecas'), ('Bibliotecas patrimoniales', 'Bibliotecas patrimoniales'), ('Audiovisual', 'Audiovisual'), ('Editorial', 'Editorial'), ('Fonográfica', 'Fonográfica'), ('Museos ', 'Museos '), ('Museos patrimoniales', 'Museos patrimoniales'), ('Actos festivos y lúdicos', 'Actos festivos y lúdicos'), ('Conocimientos tradicionales sobre la naturaleza y el universo', 'Conocimientos tradicionales sobre la naturaleza y el universo'), ('Conocimientos y técnicas tradicionales asociadas al hábitat', 'Conocimientos y técnicas tradicionales asociadas al hábitat'), ('Cultura culinaria', 'Cultura culinaria'), ('Eventos religiosos tradicionales de carácter colectivo', 'Eventos religiosos tradicionales de carácter colectivo'), ('Juegos y deportes tradicionales', 'Juegos y deportes tradicionales'), ('Lenguas, lenguajes y tradición oral', 'Lenguas, lenguajes y tradición oral'), ('Medicina tradicional', 'Medicina tradicional'), ('PCI asociado a espacios culturales', 'PCI asociado a espacios culturales'), ('PCI asociado a los eventos de la vida cotidiana', 'PCI asociado a los eventos de la vida cotidiana'), ('Producción tradicional y propia', 'Producción tradicional y propia'), ('Sistemas normativos y formas de organización social tradicionales', 'Sistemas normativos y formas de organización social tradicionales'), ('Técnicas y tradicionales asociadas a la fabricación de objetos artesanales', 'Técnicas y tradicionales asociadas a la fabricación de objetos artesanales'), ('Museos patrimoniales', 'Museos patrimoniales')], max_length=82, null=True, verbose_name='7.1.  ¿ÁREAS ARTÍSTICAS EN LAS QUE IMPARTE FORMACIÓN?')),
                ('modalidad', models.CharField(blank=True, choices=[('FORMAL', 'FORMAL'), ('NO FORMAL', 'NO FORMAL')], max_length=82, null=True, verbose_name='7.2.  PRINCIPAL MODALIDAD DE FORMACIÓN QUE IMPARTE LA ORGANIZACIÓN')),
                ('terminosycondiciones', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Acepta terminos y condiciones')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('caracter_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.caracterentidad', verbose_name='3.6. CARÁCTER DE LA ENTIDAD:')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.city', verbose_name='2.1. MUNICIPIO')),
                ('etnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.groupetnico', verbose_name='6.12. ¿HACÍA CUALES MINORÍAS ÉTNICAS SE ENFOCAN ESTOS PROGRAMAS O PROYECTOS?')),
                ('formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.formacione', verbose_name='3.2. FORMACIÓN')),
                ('naturaleza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.naturaleza', verbose_name='3.5. NATURALEZA:')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.regimen', verbose_name='3.8. TIPO DE REGIMEN')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.region', verbose_name='2.DEPARTAMENTO')),
                ('subregimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.subregimen', verbose_name='3.9. SUBREGIMEN:')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.typedocument', verbose_name='1.10. TIPO DOCUMENTO IDENTIDAD:')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrador de la entidad')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agentcultural.region', verbose_name='Departamento'),
        ),
        migrations.CreateModel(
            name='AgentCultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('AGENTE CULTURAL', 'AGENTE CULTURAL'), ('GESTOR CULTURAL', 'GESTOR CULTURAL')], max_length=17, null=True, verbose_name='1.AGENTE O GESTOR CULTURAL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='agent/image', verbose_name='Imagen del agente')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='1.1. NOMBRES')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='1.2. APELLIDOS')),
                ('artistic_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='1.3. NOMBRE ARTÍSTICO')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='1.5. FECHA DE NACIMIENTO')),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=30, null=True, verbose_name='1.6. LUGAR DE NACIMIENTO')),
                ('identification', models.IntegerField(blank=True, max_length=30, null=True, verbose_name='1.8. NÚMERO DE DOCUMENTO')),
                ('lugar_expedicion', models.CharField(blank=True, max_length=30, null=True, verbose_name='1.9. LUGAR DE EXPEDICIÓN')),
                ('tarjeta_profesional', models.CharField(blank=True, max_length=30, null=True, verbose_name='1.10. TARJETA PROFESIONAL')),
                ('expedicion_tarjeta', models.DateField(blank=True, null=True, verbose_name='1.11. FECHA DE EXPEDICIÓN')),
                ('passport', models.CharField(blank=True, max_length=30, null=True, verbose_name='1.12. PASAPORTE')),
                ('expedicion_passport', models.DateField(blank=True, null=True, verbose_name='1.13. FECHA DE EXPEDICIÓN')),
                ('vencimiento_passport', models.DateField(blank=True, null=True, verbose_name='1.14. FECHA DE VENCIMIENTO')),
                ('posee_discapacidad', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='1.15. ¿POSEE ALGUNA DISCAPACIDAD FÍSICA?')),
                ('posee_etnico', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='1.17. ¿PERTENECE A UNA MINORÍA ÉTNICA?')),
                ('esvictima', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='1.19. ¿ES VÍCTIMA?')),
                ('zona', models.CharField(blank=True, choices=[('URBANA', 'URBANA'), ('RURAL', 'RURAL')], max_length=10, null=True, verbose_name='2.2. ÁREA')),
                ('adress', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.3. DIRECCIÓN DE VIVIENDA')),
                ('adress2', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.4. DIRECCIÓN DE CORRESPONDENCIA')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.5. TELÉFONO')),
                ('phone_movil', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.6. CELULAR ')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='2.7. E-MAIL')),
                ('web', models.EmailField(blank=True, max_length=30, null=True, verbose_name='2.8. PÁGINA WEB')),
                ('desarrollo_practica', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.1. ¿ACTUALMENTE DESARROLLA ALGUNA PRÁCTICA ARTÍSTICA?')),
                ('forma_practica', models.CharField(blank=True, choices=[('AFICIONADO', 'AFICIONADO'), ('PROFESIONAL', 'PROFESIONAL')], max_length=50, null=True, verbose_name='3.2. DESARROLLA LA PRÁCTICA ARTÍSTICA DE FORMA')),
                ('area2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MÚSICA', 'MÚSICA'), ('DANZA', 'DANZA'), ('TEATRO', 'TEATRO'), ('CIRCO', 'CIRCO'), ('ARTES PLÁSTICAS Y VISUALES', 'ARTES PLÁSTICAS Y VISUALES'), ('CINEMATOGRAFÍA', 'CINEMATOGRAFÍA'), ('GASTRONIMÍA', 'GASTRONOMÍA'), ('LITERATURA', 'LITERATURA'), ('PATRIMONIO', 'PATRIMONIO')], max_length=101, null=True, verbose_name='3.3. ÁREA ARTÍSTICA QUE PRACTICA')),
                ('practica', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DIRECTOR', 'DIRECTOR'), ('GESTOR', 'GESTOR'), ('TÉCNICO', 'TÉCNICO'), ('FORMADOR', 'FORMADOR'), ('PRODUCTOR', 'PRODUCTOR'), ('COMPOSITOR', 'COMPOSITOR'), ('CRÍTICO', 'CRÍTICO'), ('PROMOTOR', 'PROMOTOR'), ('INVESTIGADOR', 'INVESTIGADOR'), ('INGENIERO DE SONIDO', 'INGENIERO DE SONIDO'), ('INTÉRPRETE', 'INTÉRPRETE'), ('LUTHIER', 'LUTHIER'), ('ARREGLISTA', 'ARREGLISTA'), ('GUIONISTA', 'GUIONISTA'), ('REALIZADOR', 'REALIZADOR'), ('EXHIBIDOR', 'EXHIBIDOR'), ('DISTRIBUIDOR', 'DISTRIBUIDOR'), ('RESTAURADOR', 'RESTAURADOR'), ('PINTOR', 'PINTOR'), ('ESCULTOR', 'ESCULTOR'), ('CURADOR', 'CURADOR'), ('GALERISTA', 'GALERISTA'), ('DISEÑADOR', 'DISEÑADOR'), ('FOTÓGRAFO', 'FOTÓGRAFO'), ('VIDEO ARTISTA', 'VIDEO ARTISTA'), ('ACTOR/ACTRIZ', 'ACTOR/ACTRIZ'), ('VESTUARISTA', 'VESTUARISTA'), ('ESCENÓGRAFO', 'ESCENÓGRAFO'), ('BAILARÍN', 'BAILARÍN'), ('COREÓGRAFO', 'COREÓGRAFO'), ('DRAMATURGO', 'DRAMATURGO'), ('EDITOR', 'EDITOR'), ('ESCRITOR', 'ESCRITOR'), ('LIBRERO', 'LIBRERO'), ('OTRAS', 'OTRAS')], max_length=355, null=True, verbose_name='3.4. PRÁCTICA ARTÍSTICA')),
                ('cual_practica', models.CharField(blank=True, max_length=30, null=True, verbose_name='3.4. ¿CUÁL?')),
                ('pertenece_entidad', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.5. ¿PERTENECE A UNA ORGANIZACIÓN ARTÍSTICA O CULTURAL?')),
                ('vinculacion_entidad', models.DateField(blank=True, null=True, verbose_name='3.6. ¿DESDE QUÉ AÑO ESTÁ VINCULADO A LA ORGANIZACIÓN ARTÍSTICA O CULTURAL?')),
                ('name_entity', models.CharField(blank=True, max_length=30, null=True, verbose_name='3.7. NOMBRE DE LA ORGANIZACIÓN ARTÍSTICA O CULTURAL')),
                ('tipo_formacion', models.CharField(blank=True, choices=[('FORMAL', 'FORMAL'), ('NO FORMAL', 'NO FORMAL')], max_length=40, null=True, verbose_name='3.8. ¿QUÉ TIPO DE FORMACIÓN HA RECIBIDO?:')),
                ('nivel_educacion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PRIMARIA INCOMPLETA', 'PRIMARIA INCOMPLETA'), ('PRIMARIA COMPLETA', 'PRIMARIA COMPLETA'), ('SECUNDARIA INCOMPLETA', 'SECUNDARIA INCOMPLETA'), ('SECUNDARIA COMPLETA', 'SECUNDARIA COMPLETA'), ('UNIVERSITARIO SIN TÍTULO', 'UNIVERSITARIO SIN TÍTULO'), ('UNIVERSITARIO CON TÍTULO', 'UNIVERSITARIO CON TÍTULO'), ('AUTODIDACTA', 'AUTODIDACTA'), ('TÉCNICO/TECNÓLOGO', 'TÉCNICO/TECNÓLOGO'), ('POSTGRADO', 'POSTGRADO'), ('OTRA', 'OTRA')], max_length=174, null=True, verbose_name='3.9. NIVEL DE EDUCACIÓN')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='3.10.TÍTULO RECIBIDO')),
                ('ano_titulo', models.DateField(blank=True, null=True, verbose_name='3.11. AÑO ')),
                ('entidad_educativa', models.CharField(blank=True, max_length=60, null=True, verbose_name='3.12. NOMBRE DE ENTIDAD EDUCATIVA')),
                ('reseña_trayectoria', models.TextField(blank=True, max_length=2000, null=True, verbose_name='3.13. RESEÑA TRAYECTORIA ARTÍSTICA')),
                ('tipo_vivienda', models.CharField(blank=True, choices=[('PROPIO', 'PROPIO'), ('EN ARRIENDO', 'EN ARRIENDO'), ('EN COMODATO', 'EN COMODATO'), ('PRESTAMO', 'PRESTAMO'), ('NO TIENE', 'NO TIENE')], max_length=40, null=True, verbose_name='4.1. LA VIVIENDA QUE HABITA ES:')),
                ('tipo_vinculacion', models.CharField(blank=True, choices=[('LABORAL PERMANENTE', 'LABORAL PERMANENTE'), ('CONTRATISTA', 'CONTRATISTA'), ('OTRO', 'OTRO')], max_length=40, null=True, verbose_name='4.3. ¿TIPO DE VINCULACIÓN EN LA ACTIVIDAD ARTÍSTICA Y CULTURAL?:')),
                ('cual_vinculacion', models.CharField(blank=True, max_length=40, null=True, verbose_name='4.3.1. ¿CUÁL TIPO DE VINCULACIÓN?:')),
                ('otra_actividad', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.4. ¿DESARROLLA OTRA ACTIVIDAD PRODUCTIVA DIFERENTE A LA ARTÍSTICA Y CULTURAL?')),
                ('fuente_ingreso', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LA ACTIVIDAD ARTÍSTICA Y CULTURAL ES SU PRINCIPAL FUENTE DE INGRESO', 'LA ACTIVIDAD ARTÍSTICA Y CULTURAL ES SU PRINCIPAL FUENTE DE INGRESO'), ('LA ACTIVIDAD ARTÍSTICA Y CULTURAL ES SU FUENTE ALTERNATIVA DE INGRESO', 'LA ACTIVIDAD ARTÍSTICA Y CULTURAL ES SU FUENTE ALTERNATIVA DE INGRESO'), ('NO RECIBE INGRESO POR CONCEPTO DE SU ACTIVIDAD ARTÍSTICA Y CULTURAL', 'NO RECIBE INGRESO POR CONCEPTO DE SU ACTIVIDAD ARTÍSTICA Y CULTURAL')], max_length=205, null=True, verbose_name='4.5. FUENTES DE INGRESO')),
                ('porcentaje', models.IntegerField(blank=True, max_length=30, null=True, verbose_name='4.6. ¿QUÉ PORCENTAJE DE SUS INGREOS PROVIENEN DE LA ACTIVIDAD ARTÍSTICA Y CULTURAL?')),
                ('regimen_salud', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.7. SE ENCUENTRA ACTUALMENTE AFILIADO AL RÉGIMEN DE SEGURIDAD SOCIAL EN SALUD?')),
                ('regimen_pension', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.9. ¿SE ENCUENTRA ACTUALMENTE AFILIADO AL RÉGIMEN DE SEGURIDAD SOCIAL EN PENSIONES?')),
                ('regimen_arl', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.11. ¿SE ENCUENTRA ACTUALMENTE AFILIADO AL RÉGIMEN DE RIESGOS PROFESIONALES?:')),
                ('vigia_patrimonio', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='VIGIA PATRIMONIO')),
                ('portador_manifestacion', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='PORTADOR DE MANIFESTACIÓN PATRIMONIO')),
                ('servicios', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Servicios que ofreces')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram')),
                ('sisben', models.FileField(blank=True, null=True, upload_to='agent/file', verbose_name='Sisben')),
                ('beps', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Tiene BEPS?')),
                ('terminosycondiciones', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Acepta terminos y condiciones')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.city', verbose_name='2.1. MUNICIPIO')),
                ('disability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.disability', verbose_name='1.16. ¿CUÁL ?')),
                ('etnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.groupetnico', verbose_name='1.18. ¿CUÁL?')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.genero', verbose_name='1.4. GÉNERO')),
                ('health_regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.healthregimen', verbose_name='4.8.  A QUE RÉGMIEN DE SALUD')),
                ('housing_stratum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.housingstratum', verbose_name='4.2. ESTRATO DE LA VIVIENDA')),
                ('manifestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.manifestation', verbose_name='MANIFESTACIÓN')),
                ('pension_regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.pensionregimen', verbose_name='4.10. A QUE RÉGIMEN DE PENSIÓN')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.typedocument', verbose_name='1.7. TIPO DOCUMENTO IDENTIDAD')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('victima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.victima', verbose_name='1.20. ¿HECHO VICTIMIZANTE?')),
            ],
            options={
                'verbose_name': 'Agente cultural',
                'verbose_name_plural': 'Agente Cultural',
            },
        ),
    ]
