# Generated by Django 3.2 on 2021-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='web',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2.8. PÁGINA WEB'),
        ),
    ]
