# Generated by Django 3.2 on 2021-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0002_alter_agentcultural_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agent/image', verbose_name='Imagen del agente'),
        ),
    ]
