# Generated by Django 3.2 on 2021-05-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0003_alter_agentcultural_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Sisben'),
        ),
    ]
