# Generated by Django 3.2 on 2021-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0004_alter_agentcultural_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcultural',
            name='archivo',
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='sisben',
            field=models.ImageField(blank=True, null=True, upload_to='agent/image', verbose_name='Sisben(subir una imagen)'),
        ),
    ]
