# Generated by Django 3.2 on 2021-05-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0005_auto_20210524_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcultural',
            name='sisben',
        ),
    ]
