# Generated by Django 3.2 on 2021-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0006_remove_agentcultural_sisben'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcultural',
            name='sisben',
            field=models.ImageField(blank=True, null=True, upload_to='agent/image', verbose_name='Sisben(subir una imagen)'),
        ),
    ]
