# Generated by Django 3.2 on 2021-05-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0007_agentcultural_sisben'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='sisben',
            field=models.FileField(blank=True, null=True, upload_to='agent/file', verbose_name='Sisben'),
        ),
    ]
