# Generated by Django 3.2 on 2021-05-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0009_entidad_camara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='camara',
        ),
    ]
