# Generated by Django 3.2 on 2021-05-31 20:49

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0010_remove_entidad_camara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='HÉCHO VICTIMIZANTE')),
            ],
            options={
                'verbose_name': 'Hecho victimizante',
                'verbose_name_plural': 'Hechos victimizantes',
            },
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='beps',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='code_rut',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='country',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='formacion',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='last_name2',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='mas_formacion',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='population_group',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='state',
        ),
        migrations.RemoveField(
            model_name='agentcultural',
            name='zone',
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='adress2',
            field=models.CharField(blank=True, max_length=30, verbose_name='2.4. DIRECCIÓN DE CORRESPONDENCIA'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='ano_titulo',
            field=models.DateField(auto_now=True, null=True, verbose_name='3.11. AÑO '),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='cual_practica',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='3.4. ¿CUÁL PRACTICA?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='cual_vinculacion',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='4.3.1. ¿CUÁL TIPO DE VINCULACIÓN?:'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='desarrollo_practica',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.1. ¿ACTUALMENTE DESARROLLA ALGUNA PRÁCTICA ARTÍSTICA?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='entidad_educativa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='3.12. NOMBRE DE ENTIDAD EDUCATIVA'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='esvictima',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='1.19. ¿ES VÍCTIMA?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='expedicion_passport',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.13. FECHA EXPEDICIÓN'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='expedicion_tarjeta',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.11. FECHA EXPEDICIÓN'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='forma_practica',
            field=models.CharField(blank=True, choices=[('AFICIONADO', 'AFICIONADO'), ('PROFESIONAL', 'PROFESIONAL')], max_length=50, null=True, verbose_name='3.2. DESARROLLA LA PRÁCTICA ARTÍSTICA DE FORMA'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='fuente_ingreso',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LA ACTIVIDAD ARTÍSTICA Y CULTURAL ES SU PRINCIPAL FUENTE DE INGRESO', 'LA ACTIVIDAD ARTÍSTICA Y CULTURAL ES SU PRINCIPAL FUENTE DE INGRESO'), ('LA ACTIVIDAD ARTÍSTICA Y CULTURAL ES SU FUENTE ALTERNATIVA DE INGRESO', 'LA ACTIVIDAD ARTÍSTICA Y CULTURAL ES SU FUENTE ALTERNATIVA DE INGRESO'), ('NO RECIBE INGRESO POR CONCEPTO DE SU ACTIVIDAD ARTÍSTICA Y CULTURAL', 'NO RECIBE INGRESO POR CONCEPTO DE SU ACTIVIDAD ARTÍSTICA Y CULTURAL')], max_length=205, null=True, verbose_name='4.5. FUENTES DE INGRESO'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='lugar_expedicion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='1.9. LUGAR DE EXPEDICIÓN'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='1.6. LUGAR DE NACIMIENTO'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='name_entity',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='3.7. NOMBRE DE LA ORGANIZACIÓN ARTÍSTICA O CULTURAL'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='nivel_educacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DIRECTOR', 'DIRECTOR'), ('GESTOR', 'GESTOR'), ('TÉCNICO', 'TÉCNICO'), ('FORMADOR', 'FORMADOR'), ('PRODUCTOR', 'PRODUCTOR'), ('COMPOSITOR', 'COMPOSITOR'), ('CRÍTICO', 'CRÍTICO'), ('PROMOTOR', 'PROMOTOR'), ('INVESTIGADOR', 'INVESTIGADOR'), ('INGENIERO DE SONIDO', 'INGENIERO DE SONIDO'), ('INTÉRPRETE', 'INTÉRPRETE'), ('LUTHIER', 'LUTHIER'), ('ARREGLISTA', 'ARREGLISTA'), ('GUIONISTA', 'GUIONISTA'), ('REALIZADOR', 'REALIZADOR'), ('EXHIBIDOR', 'EXHIBIDOR'), ('DISTRIBUIDOR', 'DISTRIBUIDOR'), ('RESTAURADOR', 'RESTAURADOR'), ('PINTOR', 'PINTOR'), ('ESCULTOR', 'ESCULTOR'), ('CURADOR', 'CURADOR'), ('GALERISTA', 'GALERISTA'), ('DISEÑADOR', 'DISEÑADOR'), ('FOTÓGRAFO', 'FOTÓGRAFO'), ('VIDEO ARTISTA', 'VIDEO ARTISTA'), ('ACTOR/ACTRIZ', 'ACTOR/ACTRIZ'), ('VESTUARISTA', 'VESTUARISTA'), ('ESCENÓGRAFO', 'ESCENÓGRAFO'), ('BAILARÍN', 'BAILARÍN'), ('COREÓGRAFO', 'COREÓGRAFO'), ('DRAMATURGO', 'DRAMATURGO'), ('EDITOR', 'EDITOR'), ('ESCRITOR', 'ESCRITOR'), ('LIBRERO', 'LIBRERO'), ('OTRAS', 'OTRAS')], max_length=355, null=True, verbose_name='3.9. NIVEL DE EDUCACIÓN'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='otra_actividad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.4. ¿DESARROLLA OTRA ACTIVIDAD PRODUCTIVA DIFERENTE A LA ARTÍSTICA Y CULTURAL?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='passport',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='1.12. PASAPORTE'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='pertenece_entidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.5. ¿PERTENECE A UNA ORGANIZACIÓN ARTÍSTICA O CULTURAL?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='porcentaje',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='4.6. ¿QUÉ PORCENTAJE DE SUS INGREOS PROVIENEN DE LA ACTIVIDAD ARTÍSTICA Y CULTURAL?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='posee_discapacidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='1.15. ¿POSEE ALGUNA DISCAPACIDAD FÍSICA?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='posee_etnico',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='1.17. ¿PERTENECE A UNA MINORÍA ÉTNICA?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='practica',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DIRECTOR', 'DIRECTOR'), ('GESTOR', 'GESTOR'), ('TÉCNICO', 'TÉCNICO'), ('FORMADOR', 'FORMADOR'), ('PRODUCTOR', 'PRODUCTOR'), ('COMPOSITOR', 'COMPOSITOR'), ('CRÍTICO', 'CRÍTICO'), ('PROMOTOR', 'PROMOTOR'), ('INVESTIGADOR', 'INVESTIGADOR'), ('INGENIERO DE SONIDO', 'INGENIERO DE SONIDO'), ('INTÉRPRETE', 'INTÉRPRETE'), ('LUTHIER', 'LUTHIER'), ('ARREGLISTA', 'ARREGLISTA'), ('GUIONISTA', 'GUIONISTA'), ('REALIZADOR', 'REALIZADOR'), ('EXHIBIDOR', 'EXHIBIDOR'), ('DISTRIBUIDOR', 'DISTRIBUIDOR'), ('RESTAURADOR', 'RESTAURADOR'), ('PINTOR', 'PINTOR'), ('ESCULTOR', 'ESCULTOR'), ('CURADOR', 'CURADOR'), ('GALERISTA', 'GALERISTA'), ('DISEÑADOR', 'DISEÑADOR'), ('FOTÓGRAFO', 'FOTÓGRAFO'), ('VIDEO ARTISTA', 'VIDEO ARTISTA'), ('ACTOR/ACTRIZ', 'ACTOR/ACTRIZ'), ('VESTUARISTA', 'VESTUARISTA'), ('ESCENÓGRAFO', 'ESCENÓGRAFO'), ('BAILARÍN', 'BAILARÍN'), ('COREÓGRAFO', 'COREÓGRAFO'), ('DRAMATURGO', 'DRAMATURGO'), ('EDITOR', 'EDITOR'), ('ESCRITOR', 'ESCRITOR'), ('LIBRERO', 'LIBRERO'), ('OTRAS', 'OTRAS')], max_length=355, null=True, verbose_name='3.4. PRÁCTICA ARTÍSTICA'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='regimen_arl',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.9. SE ENCUENTRA ACTUALMENTE AFILIAADO AL RÉGIMEN DE RIESGOS PROFESIONALES'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='regimen_pension',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.9. SE ENCUENTRA ACTUALMENTE AFILIAADO AL RÉGIMEN DE SEGURIDAD SOCIAL EN PENSIONES?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='regimen_salud',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.7. SE ENCUENTRA ACTUALMENTE AFILIAADO AL RÉGIMEN DE SEGURIDAD SOCIAL EN SALUD?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='reseña_trayectoria',
            field=models.TextField(blank=True, max_length=2000, verbose_name='3.13. RESEÑA TRAYECTORIA ARTÍSTICA'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='tarjeta_profesional',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='1.10. TARJETA PROFESIONAL'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='tipo_formacion',
            field=models.CharField(blank=True, choices=[('FORMAL', 'FORMAL'), ('NO FORMAL', 'NO FORMAL')], max_length=40, null=True, verbose_name='3.8. ¿QUÉ TIPO DE FORMACIÓN HA RECIBIDO?:'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='tipo_vinculacion',
            field=models.CharField(blank=True, choices=[('LABORAL PERMANENTE', 'LABORAL PERMANENTE'), ('CONTRATISTA', 'CONTRATISTA'), ('OTRO', 'OTRO')], max_length=40, null=True, verbose_name='4.3. ¿TIPO DE VINCULACIÓN EN LA ACTIVIDAD ARTÍSTICA Y CULTURAL?:'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('PROPIO', 'PROPIO'), ('EN ARRIENDO', 'EN ARRIENDO'), ('EN COMODATO', 'EN COMODATO'), ('PRESTAMO', 'PRESTAMO'), ('NO TIENE', 'NO TIENE')], max_length=40, null=True, verbose_name='4.1. LA VIVIENDA QUE HABITA ES:'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='titulo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='3.10.TÍTULO RECIBIDO'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='vencimiento_passport',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.14. FECHA VENCIMIENTO'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='vinculacion_entidad',
            field=models.DateField(auto_now=True, null=True, verbose_name='3.6. ¿DESDE QUÉ AÑO ESTÁ VINCULADO A LA ORGANIZACIÓN ARTÍSTICA O CULTURAL?'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='web',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='2.8. PÁGINA WEB'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='adress',
            field=models.CharField(blank=True, max_length=30, verbose_name='2.3. DIRECCIÓN DE VIVIENDA'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='area2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MÚSICA', 'MÚSICA'), ('DANZA', 'DANZA'), ('TEATRO', 'TEATRO'), ('CIRCO', 'CIRCO'), ('ARTES PLÁSTICAS Y VISUALES', 'ARTES PLÁSTICAS Y VISUALES'), ('CINEMATOGRAFÍA', 'CINEMATOGRAFÍA')], max_length=67, null=True, verbose_name='3.3. ÁREA ARTÍSTICA QUE PRACTICA'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='artistic_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='1.3. NOMBRE ARTÍSTICO'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='birthday',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.5. FECHA DE NACIMIENTO'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.city', verbose_name='2.1. MUNICIPIO'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.disability', verbose_name='1.16. ¿CUÁL DISCAPACIDAD?'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='2.7. E-MAIL'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='etnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.groupetnico', verbose_name='1.18. ¿CUÁL MINORÍA ÉTNICA?'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.genero', verbose_name='1.4. GÉNERO'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='health_regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.healthregimen', verbose_name='4.8.  A QUE RÉGMIEN DE SALUD'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='housing_stratum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.housingstratum', verbose_name='4.2. ESTRATO DE VIVIENDA'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='identification',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='1.8. NÚMERO DE DOCUMENTO'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='1.2. APELLIDOS'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='1.1. NOMBRES'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='pension_regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.pensionregimen', verbose_name='4.10. A QUE RÉGIMEN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='2.5. TELÉFONO'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='phone_movil',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='2.6. CELULAR '),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='tipo',
            field=models.CharField(blank=True, choices=[('AGENTE CULTURAL', 'AGENTE CULTURAL'), ('GESTOR CULTURAL', 'GESTOR CULTURAL')], max_length=17, null=True, verbose_name='1. ERES AGENTE O GESTOR CULTURAL'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='type_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.typedocument', verbose_name='1.7. TIPO DOCMENTO IDENTIDAD'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='zona',
            field=models.CharField(blank=True, choices=[('URBANA', 'URBANA'), ('RURAL', 'RURAL')], max_length=10, null=True, verbose_name='2.2. ÁREA'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='victima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.victima', verbose_name='1.20. ¿HECHO VICTIMIZANTE?'),
        ),
    ]
