# Generated by Django 3.2 on 2021-05-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0011_auto_20210531_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='birthday',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='1.5. FECHA DE NACIMIENTO'),
        ),
    ]
