# Generated by Django 3.2 on 2021-05-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0012_alter_agentcultural_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='birthday',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='1.5. FECHA DE NACIMIENTO'),
        ),
    ]
