# Generated by Django 3.2 on 2021-05-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0013_alter_agentcultural_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcultural',
            name='beps',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Tiene BEPS?'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='birthday',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.5. FECHA DE NACIMIENTO'),
        ),
    ]
