# Generated by Django 3.2 on 2021-05-31 21:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0014_auto_20210531_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='nivel_educacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PRIMARIA INCOMPLETA', 'PRIMARIA INCOMPLETA'), ('PRIMARIA COMPLETA', 'PRIMARIA COMPLETA'), ('SECUNDARIA INCOMPLETA', 'SECUNDARIA INCOMPLETA'), ('SECUNDARIA COMPLETA', 'SECUNDARIA COMPLETA'), ('UNIVERSITARIO SIN TÍTULO', 'UNIVERSITARIO SIN TÍTULO'), ('UNIVERSITARIO CON TÍTULO', 'UNIVERSITARIO CON TÍTULO'), ('AUTODIDACTA', 'AUTODIDACTA'), ('TÉCNICO/TECNÓLOGO', 'TÉCNICO/TECNÓLOGO'), ('POSTGRADO', 'POSTGRADO'), ('OTRA', 'OTRA')], max_length=174, null=True, verbose_name='3.9. NIVEL DE EDUCACIÓN'),
        ),
    ]
