# Generated by Django 3.2 on 2021-06-02 18:34

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0015_alter_agentcultural_nivel_educacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='cargo_representante',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.8. CARGO DEL REPRESENTANTE'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='objeto_social',
            field=models.TextField(blank=True, max_length=2000, verbose_name='OBJETO SOCIAL'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='vinculacion_representante',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='1.9. AÑO DE VINCULACIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='manifestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.manifestation', verbose_name='MANIFESTACIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='portador_manifestacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='PORTADOR DE MANIFESTACIÓN PATRIMONIO'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='regimen_arl',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.11. SE ENCUENTRA ACTUALMENTE AFILIAADO AL RÉGIMEN DE RIESGOS PROFESIONALES'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='vigia_patrimonio',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='VIGIA PATRIMONIO'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='apellidos_contacto',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.14. APELLIDOS DEL CONTACTO'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='apellidos_representante',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.7. APELLIDOS REPRESENTANTE LEGAL'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cargo',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.15. CARGO DEL CONTACTO'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='1.4. AÑO DE CONSTITUCIÓN'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='formacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.formacione', verbose_name='FORMACIÓN'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='identification',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='1.11. NÚMERO DE DOCUMENTO'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='lugar_expedicion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='1.12. LUGAR DE EXPEDICIÓN:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.1. NOMBRE:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='1.3. NIT:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.13. NOMBRES DEL CONTACTO'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre_representante',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.6. NOMBRES REPRESENTATE LEGAL: '),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='practica',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DANZA - CONTEMPORANEA', 'DANZA - CONTEMPORANEA'), ('DANZA - BALLET', 'DANZA - BALLET'), ('DANZA - URBANA', 'DANZA - URBANA'), ('DANZA - FOLCLOR', 'DANZA - FOLCLOR'), ('MÚSICA - BANDAS', 'MÚSICA - BANDAS'), ('MÚSICA - COROS', 'MÚSICA - COROS'), ('MÚSICA - ORQUESTA SINFÓNICA', 'MÚSICA - ORQUESTA SINFÓNICA'), ('MÚSICA - AGRUPACIONES MÚSICA TRADICIONAL', 'MÚSICA - AGRUPACIONES MÚSICA TRADICIONAL'), ('MÚSICA - POPULAR', 'MÚSICA - POPULAR'), ('MÚSICA - AGRUPACIONES MÚSICA ACADÉMICA', 'MÚSICA - AGRUPACIONES MÚSICA ACADÉMICA'), ('TEATRO - DE SALA', 'TEATRO - DE SALA'), ('TEATRO - TITERES', 'TEATRO - TITERES'), ('TEATRO - MUSICAL', 'TEATRO - MUSICAL'), ('TEATRO - PARA ESPACIOS NO CONVENCIONALES', 'TEATRO - PARA ESPACIOS NO CONVENCIONALES'), ('LITERATURA - EDITORIALES', 'LITERATURA - EDITORIALES'), ('LITERATURA - REVISTAS', 'LITERATURA - REVISTAS'), ('LITERATURA - TALLERES', 'LITERATURA - TALLERES'), ('LITERATURA - INSTITUCIONES LITERARIAS', 'LITERATURA - INSTITUCIONES LITERARIAS'), ('TEATRO - UNIVERSIDADES', 'TEATRO - UNIVERSIDADES'), ('TEATRO - CÀMARA DEL LIBRO', 'TEATRO - CÀMARA DEL LIBRO'), ('ARTES - PLÁSTICA', 'ARTES - PLÁSTICA'), ('ARTES - VISUAL', 'ARTES - VISUAL'), ('CINEMATOGRAFÍA', 'CINEMATOGRAFÍA')], max_length=82, null=True, verbose_name='PRACTICA ARTÍSTICA:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='reseña',
            field=models.TextField(blank=True, null=True, verbose_name='1.5. RESEÑA'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='sigla',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.2. SIGLA:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='type_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.typedocument', verbose_name='1.10. TIPO DOCUMENTO IDENTIDAD:'),
        ),
    ]
