# Generated by Django 3.2 on 2021-06-02 18:59

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0016_auto_20210602_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='zone',
        ),
        migrations.AddField(
            model_name='entidad',
            name='ultimo_año',
            field=models.CharField(blank=True, choices=[('GRATUITO Y PÚBLICO', 'GRATUITO Y PÚBLICO'), ('GRATUITO RESTRINGIDO', 'GRATUITO RESTRINGIDO'), ('PAGO', 'PAGO'), ('APORTE', 'APORTE'), ('VOLUNTARIO', 'VOLUNTARIO'), ('OTRO', 'OTRO')], max_length=22, null=True, verbose_name=' 6.6. DURANTE EL ÚLTIMO AÑO EL PROMEDIO MENSUAL APROXIMADO DE PERSONAS (PÚBLICO) QUE ASISTIERON A LA ACTIVIDAD ARTÍSTICA O CULTURAL DE LA ORGANIZACIÓ FUE: '),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='acceso',
            field=models.CharField(blank=True, choices=[('GRATUITO Y PÚBLICO', 'GRATUITO Y PÚBLICO'), ('GRATUITO RESTRINGIDO', 'GRATUITO RESTRINGIDO'), ('PAGO', 'PAGO'), ('APORTE', 'APORTE'), ('VOLUNTARIO', 'VOLUNTARIO'), ('OTRO', 'OTRO')], max_length=22, null=True, verbose_name=' 6.7. EL ACCESO DEL PÚBLICO AL RESULTADO DE LA PRÁCTICA ARTÍSTICA QUE DESARROLLA LA ORGANIZACIÓN ES DE CARÁCTER '),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='acceso_internet',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.1. ¿TIENE LA ORGANIZACIÓN ACCESOS A INTERNET?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='actividad_principal',
            field=models.CharField(blank=True, choices=[('FORMACIÓN', 'FORMACIÓN'), ('PRÁCTICA ARTISTICA', 'PRÁCTICA ARTISTICA'), ('GESTIÓN', 'GESTIÓN'), ('CIRCULACIÓN Y COMERCIALIZACIÓN', 'CIRCULACIÓN Y COMERCIALIZACIÓN')], max_length=42, null=True, verbose_name='6.1. EL CAMPO DE LA PRINCIPAL ACTIVIDAD ARTÍSTICA O CULTURAL QUE DESARROLLA LA ORGANIZACIÓN ES'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='apartado_aereo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='2.7. APARTADO AÉREO'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='apellidos_contacto',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.14. APELLIDOS DEL CONTACTO:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='area_artistica',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Artes Visuales', 'Artes Visuales'), ('Cine y audiovisuales', 'Cine y audiovisuales'), ('Circo', 'Circo'), ('Danza', 'Danza'), ('Literatura y editorial', 'Literatura y editorial'), ('Musica ', 'Musica '), ('Teatro', 'Teatro'), ('Bibiliotecas', 'Bibiliotecas'), ('Bibliotecas patrimoniales', 'Bibliotecas patrimoniales'), ('Audiovisual', 'Audiovisual'), ('Editorial', 'Editorial'), ('Fonográfica', 'Fonográfica'), ('Museos ', 'Museos '), ('Museos patrimoniales', 'Museos patrimoniales'), ('Actos festivos y lúdicos', 'Actos festivos y lúdicos'), ('Conocimientos tradicionales sobre la naturaleza y el universo', 'Conocimientos tradicionales sobre la naturaleza y el universo'), ('Conocimientos y técnicas tradicionales asociadas al hábitat', 'Conocimientos y técnicas tradicionales asociadas al hábitat'), ('Cultura culinaria', 'Cultura culinaria'), ('Eventos religiosos tradicionales de carácter colectivo', 'Eventos religiosos tradicionales de carácter colectivo'), ('Juegos y deportes tradicionales', 'Juegos y deportes tradicionales'), ('Lenguas, lenguajes y tradicion oral', 'Lenguas, lenguajes y tradicion oral'), ('Medicina tradicional', 'Medicina tradicional'), ('PCI asociado a espacios culturales', 'PCI asociado a espacios culturales'), ('PCI asociado a los evenos de la vida cotidiana', 'PCI asociado a los evenos de la vida cotidiana'), ('Produccion tradicional y propia', 'Produccion tradicional y propia'), ('Sistemas normativos y formas de organizacion social tradicionales', 'Sistemas normativos y formas de organizacion social tradicionales'), ('Técnicas y tradicionales asociadas a la fabricación de objetos artesanales', 'Técnicas y tradicionales asociadas a la fabricación de objetos artesanales'), ('Museos patrimoniales', 'Museos patrimoniales')], max_length=82, null=True, verbose_name='6.3. EL ÁREA ARTÍSTICA EN LA QUE LA ORGANIZACIÓN DESARROLLA SU PRINCIPAL ACTIVIDAD ES:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cantidad_noremunerado',
            field=models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.3. ¿CUÁNTOS EMPLEOS NO REMUNERADOS GENERÓ?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cantidad_remunerado',
            field=models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.5. ¿CUÁNTOS EMPLEOS REMUNERADOS GENERÓ?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cantidadrecurso_humano',
            field=models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.9. ¿CANTIDAD DE RECURSO HUMANO CON EL QUE CUENTA LA ENTIDAD?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cantidadremunerado_laboral',
            field=models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.8. ¿CUÁNTOS EMPLEOS REMUNERADOS GENERÓ POR CONTRATO LABORAL?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cantidadremunerado_ops',
            field=models.IntegerField(blank=True, max_length=22, null=True, verbose_name='5.7. ¿CUÁNTOS EMPLEOS REMUNERADOS GENERÓ POR CONTRATOS DE SERVICIOS?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='caracter_entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.caracterentidad', verbose_name='3.6. CARÁCTER DE LA ENTIDAD:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cargo',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.15. CARGO DEL CONTACTO:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.city', verbose_name='2.1. MUNICIPIO'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='correspondencia',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2.4. DIRECCIÓN CORRESPONDENCIA:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='dependencia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.10. DEPENDE DE ALGUNA ENTIDAD:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='direccion',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2.3. DIRECCIÓN'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='duracion_noremunerados',
            field=models.CharField(blank=True, choices=[('1 - 4 MESES', 'INTERNACIONAL'), ('5 - 8 MESES', 'NACIONAL'), ('MAS DE 8 MESES', 'DEPARTAMENTAL')], max_length=22, null=True, verbose_name='5.4. ¿QUÉ DURACIÓN TUVIERON LOS EMPLEOS NO REMUNERADOS QUE GENERÓ?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='duracion_remunerados',
            field=models.CharField(blank=True, choices=[('1 - 4 MESES', 'INTERNACIONAL'), ('5 - 8 MESES', 'NACIONAL'), ('MAS DE 8 MESES', 'DEPARTAMENTAL')], max_length=22, null=True, verbose_name='5.6. ¿QUÉ DURACIÓN TUVIERON LOS EMPLEOS REMUNERADOS QUE GENERÓ?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='2.8. E-MAIL:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='entidad_dependiente',
            field=models.CharField(blank=True, max_length=30, verbose_name='3.11. NOMBRE DE LA ENTIDAD:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='espacio',
            field=models.CharField(blank=True, choices=[('PROPIO', 'PROPIO'), ('EN ARRIENDO', 'EN ARRIENDO'), ('EN COMODATO', 'EN COMODATO'), ('PRESTAMO', 'PRESTAMO'), ('NO TIENE', 'NO TIENE')], max_length=22, null=True, verbose_name='4.2. ESPACIO'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='espacios_actividades',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AUDITORIOS', 'AUDITORIOS'), ('AULAS', 'AULAS'), ('BIBLIOTECAS', 'BIBLIOTECAS'), ('CENTROS DE DOCUMENTACIÓN', 'CENTROS DE DOCUMENTACIÓN'), ('ESTUDIOS DE PRODUCCIÓN', 'ESTUDIOS DE PRODUCCIÓN'), ('GALERÍAS', 'GALERÍAS'), ('MUSEOS', 'MUSEOS'), ('OFICINAS', 'OFICINAS'), ('PUNTOS DE VENTA', 'PUNTOS DE VENTA'), ('SALAS DE ENSAYO', 'SALAS DE ENSAYO'), ('SALAS DE ESTUDIO INDIVIDUAL', 'SALAS DE ESTUDIO INDIVIDUAL'), ('SALAS DE EXHIBICIÓN', 'SALAS DE EXHIBICIÓN'), ('SALAS DE REUNIÓN', 'SALAS DE REUNIÓN'), ('TALLERES', 'TALLERES'), ('TEATROS', 'TEATROS')], max_length=29, null=True, verbose_name='4.6. ESPACIOS DISPONIBLES POR LA ORGANIZACIÓN PARA EL DESARROLLO DE SUS ACTIVIDADES'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='etnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.groupetnico', verbose_name='6.11. ¿HACÍA CUALES MINORÍAS ÉTNICAS SE ENFOCAN ESTOS PROGRAMAS O PROYECTOS?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='formacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.formacione', verbose_name='3.2. FORMACIÓN'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='genero_empleo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=22, null=True, verbose_name='5.1. ¿SU ORGANIACIÓN GENERÓ EMPLEO DIRECTO EL ÚLTIMO AÑO?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='grupos_edad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INFANCIA', 'INFANCIA'), ('JUVENTUD', 'JUVENTUD'), ('ADULTOS', 'ADULTOS'), ('TERCERA EDAD', 'TERCERA EDAD'), ('TODOS', 'TODOS')], max_length=22, null=True, verbose_name='6.9. ¿HACIA CUÁLES GRUPOS DE EDAD SE ENFOCAN ESOS PROGRAMAS O PROYECTOS?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='grupos_poblacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INFANCIA', 'INFANCIA'), ('JUVENTUD', 'JUVENTUD'), ('ADULTOS', 'ADULTOS'), ('TERCERA EDAD', 'TERCERA EDAD'), ('TODOS', 'TODOS')], max_length=22, null=True, verbose_name='6.10. ¿A QUE GRUPO PERTENECE LA POBLACIÓN BENEFICIARÍA DE LA PRODUCCIÓN ARTISTÍCA Y CULTURAL DE LA ORGANIZACIÓN?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='imparte_formacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Artes Visuales', 'Artes Visuales'), ('Cine y audiovisuales', 'Cine y audiovisuales'), ('Circo', 'Circo'), ('Danza', 'Danza'), ('Literatura y editorial', 'Literatura y editorial'), ('Musica ', 'Musica '), ('Teatro', 'Teatro'), ('Bibiliotecas', 'Bibiliotecas'), ('Bibliotecas patrimoniales', 'Bibliotecas patrimoniales'), ('Audiovisual', 'Audiovisual'), ('Editorial', 'Editorial'), ('Fonográfica', 'Fonográfica'), ('Museos ', 'Museos '), ('Museos patrimoniales', 'Museos patrimoniales'), ('Actos festivos y lúdicos', 'Actos festivos y lúdicos'), ('Conocimientos tradicionales sobre la naturaleza y el universo', 'Conocimientos tradicionales sobre la naturaleza y el universo'), ('Conocimientos y técnicas tradicionales asociadas al hábitat', 'Conocimientos y técnicas tradicionales asociadas al hábitat'), ('Cultura culinaria', 'Cultura culinaria'), ('Eventos religiosos tradicionales de carácter colectivo', 'Eventos religiosos tradicionales de carácter colectivo'), ('Juegos y deportes tradicionales', 'Juegos y deportes tradicionales'), ('Lenguas, lenguajes y tradicion oral', 'Lenguas, lenguajes y tradicion oral'), ('Medicina tradicional', 'Medicina tradicional'), ('PCI asociado a espacios culturales', 'PCI asociado a espacios culturales'), ('PCI asociado a los evenos de la vida cotidiana', 'PCI asociado a los evenos de la vida cotidiana'), ('Produccion tradicional y propia', 'Produccion tradicional y propia'), ('Sistemas normativos y formas de organizacion social tradicionales', 'Sistemas normativos y formas de organizacion social tradicionales'), ('Técnicas y tradicionales asociadas a la fabricación de objetos artesanales', 'Técnicas y tradicionales asociadas a la fabricación de objetos artesanales'), ('Museos patrimoniales', 'Museos patrimoniales')], max_length=82, null=True, verbose_name='7.1.  ¿AREAS ARTÍSTICAS EN LAS QUE IMPARTE FORMACIÓN?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='infraestructura_discapacitados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.3. CUENTA LA ENTIDAD CON INFRAESTRUCTURA PARA DISCAPACITADOS:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='interes_cultural',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.4. OCUPA LA ENTIDAD UN BIEN DE INTERÉS CULTURAL:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('FORMAL', 'FORMAL'), ('NO FORMAL', 'NO FORMAL')], max_length=82, null=True, verbose_name='7.2.  PRINCIPAL MODALIDAD DE FORMACIÓN QUE IMPARTE LA ORGANIZACIÓN'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='name_red',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='3.14. NOMBRE DE LA RED:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='naturaleza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.naturaleza', verbose_name='3.5. NATURALEZA:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nivel',
            field=models.CharField(blank=True, choices=[('INTERNACIONAL', 'INTERNACIONAL'), ('NACIONAL', 'NACIONAL'), ('DEPARTAMENTAL', 'DEPARTAMENTAL'), ('MUNICIPAL', 'MUNICIPAL')], max_length=22, null=True, verbose_name=' 3.12. NIVEL:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nivel_interescultural',
            field=models.CharField(blank=True, choices=[('INTERNACIONAL', 'INTERNACIONAL'), ('NACIONAL', 'NACIONAL'), ('DEPARTAMENTAL', 'DEPARTAMENTAL'), ('MUNICIPAL', 'MUNICIPAL')], max_length=22, null=True, verbose_name='4.5. ¿NIVEL DEL BIEN DE INTERES CULTURAL QUE OCUPA?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nivel_red',
            field=models.CharField(blank=True, choices=[('INTERNACIONAL', 'INTERNACIONAL'), ('NACIONAL', 'NACIONAL'), ('DEPARTAMENTAL', 'DEPARTAMENTAL'), ('MUNICIPAL', 'MUNICIPAL')], max_length=22, null=True, verbose_name='3.15. NIVEL:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.13. NOMBRES DEL CONTACTO:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='numero_obras',
            field=models.IntegerField(blank=True, max_length=80, null=True, verbose_name='6.4. ¿NÚMERO DE OBRAS PRODUCIDAS DURANTE EL ÚLTIMO AÑO, COMO EL RESULTADO DE LA PRÁCTICA ARTÍSTICA QUE DESARROLLA LAORGANIZACIÓN?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='objeto_social',
            field=models.TextField(blank=True, max_length=2000, verbose_name='3.7. OBJETO SOCIAL'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='organizacion_actividades',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='6.10. ¿DESARROLLA LA ORGANIZACIÓN ACTIVIDADES DIRIGIDAS A MINORÍAS ÉTNICAS?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='otra_actividad',
            field=models.CharField(blank=True, choices=[('FORMACIÓN', 'FORMACIÓN'), ('PRÁCTICA ARTISTICA', 'PRÁCTICA ARTISTICA'), ('GESTIÓN', 'GESTIÓN'), ('CIRCULACIÓN Y COMERCIALIZACIÓN', 'CIRCULACIÓN Y COMERCIALIZACIÓN')], max_length=42, null=True, verbose_name='6.2. OTROS CAMPOS DE ACTIVIDADES EN QUE TRABAJA LA ORGANIZACIÓN SON:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='2.9. PÁGINA WEB:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='personas_discapacidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='6.12. ¿DESARROLLA LA ORGANIZACIÓN ACTIVIDADES ESPECÍFICAMENTE DIRIGIDAS A PERSONAS CON DISCAPACIDAD?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='personeria',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.4. TIENE PERSONERIA JURÍDICA:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='2.6. FAX'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='phone_movil',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='2.5. TELEFONO:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='practica',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DANZA - CONTEMPORANEA', 'DANZA - CONTEMPORANEA'), ('DANZA - BALLET', 'DANZA - BALLET'), ('DANZA - URBANA', 'DANZA - URBANA'), ('DANZA - FOLCLOR', 'DANZA - FOLCLOR'), ('MÚSICA - BANDAS', 'MÚSICA - BANDAS'), ('MÚSICA - COROS', 'MÚSICA - COROS'), ('MÚSICA - ORQUESTA SINFÓNICA', 'MÚSICA - ORQUESTA SINFÓNICA'), ('MÚSICA - AGRUPACIONES MÚSICA TRADICIONAL', 'MÚSICA - AGRUPACIONES MÚSICA TRADICIONAL'), ('MÚSICA - POPULAR', 'MÚSICA - POPULAR'), ('MÚSICA - AGRUPACIONES MÚSICA ACADÉMICA', 'MÚSICA - AGRUPACIONES MÚSICA ACADÉMICA'), ('TEATRO - DE SALA', 'TEATRO - DE SALA'), ('TEATRO - TITERES', 'TEATRO - TITERES'), ('TEATRO - MUSICAL', 'TEATRO - MUSICAL'), ('TEATRO - PARA ESPACIOS NO CONVENCIONALES', 'TEATRO - PARA ESPACIOS NO CONVENCIONALES'), ('LITERATURA - EDITORIALES', 'LITERATURA - EDITORIALES'), ('LITERATURA - REVISTAS', 'LITERATURA - REVISTAS'), ('LITERATURA - TALLERES', 'LITERATURA - TALLERES'), ('LITERATURA - INSTITUCIONES LITERARIAS', 'LITERATURA - INSTITUCIONES LITERARIAS'), ('TEATRO - UNIVERSIDADES', 'TEATRO - UNIVERSIDADES'), ('TEATRO - CÀMARA DEL LIBRO', 'TEATRO - CÀMARA DEL LIBRO'), ('ARTES - PLÁSTICA', 'ARTES - PLÁSTICA'), ('ARTES - VISUAL', 'ARTES - VISUAL'), ('CINEMATOGRAFÍA', 'CINEMATOGRAFÍA')], max_length=82, null=True, verbose_name='3.1. PRÁCTICA ARTÍSTICA:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='practicas',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='6.5. ¿LAS PRÁCTICAS ASTÍSTICAS QUE REALIZA LA ORGANIZACIÓN INCLUYEN ACTIVIDADES DE FORMACIÓN DE PÚBLICOS? '),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='proyectos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name=' 6.8. ¿LA ENTIDAD ORGANIZA REGULARMENTE PROGRAMAS O PROYECTOS ENFOCADOS ESPECÍFICAMENTE A ATENDER NIÑOS , JO¿ÓVENES, ADULTOS O PERSONAS MAYORES?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='red',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3.13. LA ENTIDAD PERTENECE A ALGUNA RED?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.regimen', verbose_name='3.8. TIPO DE REGIMEN'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.region', verbose_name='2.DEPARTAMENTO'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='subregimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.subregimen', verbose_name='3.9. SUBREGIMEN:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo_empleo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=22, null=True, verbose_name='5.2. ¿QUÉ TIPO DE EMPLEO DIRECTO GENERÓ?:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo_produccion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PRODUCCIÓN, COMERCIALIZACIÓN Y DIVULGACIÓN', 'PRODUCCIÓN, COMERCIALIZACIÓN Y DIVULGACIÓN'), ('EMPRESA FONOGRÁFICA', 'EMPRESA FONOGRÁFICA'), ('EDITORIAL', 'EDITORIAL'), ('EMPRESA EN CONSTRUCCIÓN Y REPARACIÓN DE INSTITUCIÓN', 'EMPRESA EN CONSTRUCCIÓN Y REPARACIÓN DE INSTITUCIÓN'), ('PRODUCTORA DE EVENTOS', 'PRODUCTORA DE EVENTOS'), ('REPRESENTACIÓN ARTÍSTICA', 'REPRESENTACIÓN ARTÍSTICA'), ('DISTRIBUIDORA', 'DISTRIBUIDORA'), ('GALERISTA', 'GALERISTA')], max_length=82, null=True, verbose_name='3.3. PRODUCCIÓN, COMERCIALIZACIÓN Y DIVULGACIÓN: '),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='vinculacion',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.16. AÑO DE VINCULACIÓN:'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='zona',
            field=models.CharField(blank=True, choices=[('URBANA', 'URBANA'), ('RURAL', 'RURAL')], max_length=10, null=True, verbose_name='2.2. ÁREA'),
        ),
    ]
