# Generated by Django 3.2 on 2021-06-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0017_auto_20210602_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='vinculacion_representante',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.9. AÑO DE VINCULACIÓN'),
        ),
    ]
