# Generated by Django 3.2 on 2021-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0018_alter_entidad_vinculacion_representante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='tipo',
            field=models.CharField(blank=True, choices=[('AGENTE CULTURAL', 'AGENTE CULTURAL'), ('GESTOR CULTURAL', 'GESTOR CULTURAL')], max_length=17, null=True, verbose_name='1.AGENTE O GESTOR CULTURAL'),
        ),
    ]
