# Generated by Django 3.2 on 2021-06-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0019_alter_agentcultural_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.disability', verbose_name='1.16. ¿CUÁL ?'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='etnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.groupetnico', verbose_name='1.18. ¿CUÁL?'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='expedicion_passport',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.13. FECHA DE EXPEDICIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='expedicion_tarjeta',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.11. FECHA DE EXPEDICIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='vencimiento_passport',
            field=models.DateField(auto_now=True, null=True, verbose_name='1.14. FECHA DE VENCIMIENTO'),
        ),
    ]
