# Generated by Django 3.2 on 2021-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0020_auto_20210602_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='cual_practica',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='3.4. ¿CUÁL?'),
        ),
    ]
