# Generated by Django 3.2 on 2021-06-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0021_alter_agentcultural_cual_practica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='housing_stratum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.housingstratum', verbose_name='4.2. ESTRATO DE LA VIVIENDA'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='pension_regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.pensionregimen', verbose_name='4.10. A QUE RÉGIMEN DE PENSIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='regimen_arl',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.11. ¿SE ENCUENTRA ACTUALMENTE AFILIADO AL RÉGIMEN DE RIESGOS PROFESIONALES?:'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='regimen_pension',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.9. ¿SE ENCUENTRA ACTUALMENTE AFILIADO AL RÉGIMEN DE SEGURIDAD SOCIAL EN PENSIONES?'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='regimen_salud',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='4.7. SE ENCUENTRA ACTUALMENTE AFILIADO AL RÉGIMEN DE SEGURIDAD SOCIAL EN SALUD?'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='type_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.typedocument', verbose_name='1.7. TIPO DOCUMENTO IDENTIDAD'),
        ),
    ]
