# Generated by Django 3.2 on 2021-06-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0022_auto_20210602_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='apellidos_representante',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.7. APELLIDOS DEL REPRESENTANTE LEGAL'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre_representante',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1.6. NOMBRES DEL REPRESENTATE LEGAL: '),
        ),
    ]
