# Generated by Django 3.2 on 2021-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0025_alter_entidad_personeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='genero_empleo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=22, null=True, verbose_name='5.1. ¿SU ORGANIZACIÓN GENERÓ EMPLEO DIRECTO EL ÚLTIMO AÑO?:'),
        ),
    ]
