# Generated by Django 3.2 on 2021-06-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0032_auto_20210602_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='numero_obras',
            field=models.IntegerField(blank=True, max_length=80, null=True, verbose_name='6.4. ¿NÚMERO DE OBRAS PRODUCIDAS DURANTE EL ÚLTIMO AÑO, COMO EL RESULTADO DE LA PRÁCTICA ARTÍSTICA QUE DESARROLLA LA ORGANIZACIÓN?'),
        ),
    ]
