# Generated by Django 3.2 on 2021-06-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0033_alter_entidad_numero_obras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='proyectos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name=' 6.8. ¿LA ENTIDAD ORGANIZA REGULARMENTE PROGRAMAS O PROYECTOS ENFOCADOS ESPECÍFICAMENTE A ATENDER NIÑOS , JÓVENES, ADULTOS O PERSONAS MAYORES?'),
        ),
    ]
