# Generated by Django 3.2 on 2021-06-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0035_auto_20210602_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='etnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentcultural.groupetnico', verbose_name='6.12. ¿HACÍA CUALES MINORÍAS ÉTNICAS SE ENFOCAN ESTOS PROGRAMAS O PROYECTOS?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='organizacion_actividades',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='6.11. ¿DESARROLLA LA ORGANIZACIÓN ACTIVIDADES DIRIGIDAS A MINORÍAS ÉTNICAS?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='personas_discapacidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='6.13. ¿DESARROLLA LA ORGANIZACIÓN ACTIVIDADES ESPECÍFICAMENTE DIRIGIDAS A PERSONAS CON DISCAPACIDAD?'),
        ),
    ]
