# Generated by Django 3.2 on 2021-06-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0037_alter_entidad_imparte_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcultural',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='agentcultural',
            name='servicios',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Servicios que ofreces'),
        ),
    ]
