# Generated by Django 3.2 on 2021-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0039_auto_20210708_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='reseña_trayectoria',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='3.13. RESEÑA TRAYECTORIA ARTÍSTICA'),
        ),
    ]
