# Generated by Django 3.2 on 2021-07-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0040_alter_agentcultural_reseña_trayectoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victima',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='HÉCHO VICTIMIZANTE'),
        ),
    ]
