# Generated by Django 3.2 on 2021-07-08 21:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0041_alter_victima_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='area2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MÚSICA', 'MÚSICA'), ('DANZA', 'DANZA'), ('TEATRO', 'TEATRO'), ('CIRCO', 'CIRCO'), ('ARTES PLÁSTICAS Y VISUALES', 'ARTES PLÁSTICAS Y VISUALES'), ('CINEMATOGRAFÍA', 'CINEMATOGRAFÍA'), ('GASTRONIMÍA', 'GASTRONOMÍA')], max_length=79, null=True, verbose_name='3.3. ÁREA ARTÍSTICA QUE PRACTICA'),
        ),
    ]
