# Generated by Django 3.2 on 2021-07-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0043_alter_agentcultural_area2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disability',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='TIpo de Discapacidad'),
        ),
    ]
