# Generated by Django 3.2 on 2021-08-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0045_auto_20210803_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
