# Generated by Django 3.2 on 2021-08-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0046_alter_agentcultural_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='1.5. FECHA DE NACIMIENTO'),
        ),
    ]
