# Generated by Django 3.2 on 2021-08-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0047_alter_agentcultural_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='ano_titulo',
            field=models.DateField(blank=True, null=True, verbose_name='1.4. AÑO DE CONSTITUCIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='1.4. AÑO DE CONSTITUCIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='expedicion_passport',
            field=models.DateField(blank=True, null=True, verbose_name='1.4. AÑO DE CONSTITUCIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='expedicion_tarjeta',
            field=models.DateField(blank=True, null=True, verbose_name='1.4. AÑO DE CONSTITUCIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='vencimiento_passport',
            field=models.DateField(blank=True, null=True, verbose_name='1.4. AÑO DE CONSTITUCIÓN'),
        ),
        migrations.AlterField(
            model_name='agentcultural',
            name='vinculacion_entidad',
            field=models.DateField(blank=True, null=True, verbose_name='1.4. AÑO DE CONSTITUCIÓN'),
        ),
    ]
