# Generated by Django 3.2 on 2021-08-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcultural', '0048_auto_20210803_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcultural',
            name='birthday',
            field=models.DateField(null=True, verbose_name='1.4. AÑO DE CONSTITUCIÓN'),
        ),
    ]
