# Generated by Django 3.2 on 2021-09-02 22:33

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Meta')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.region', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre de Programa')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programa',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres y Aepllidos : *')),
                ('email', models.EmailField(blank=True, max_length=20, null=True, verbose_name='Correo *')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono fijo:')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('entity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la entidad *')),
                ('iniciativa', models.TextField(blank=True, null=True, verbose_name='Iniciativa')),
                ('planteamiento', models.TextField(blank=True, null=True, verbose_name='2. Planteamiento del Problema:')),
                ('objetivo_general', models.TextField(blank=True, null=True, verbose_name='3.1. Objetivo General')),
                ('objetivo_especifico', models.TextField(blank=True, null=True, verbose_name='3.2 Objetivos Específicos:')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='4. Breve Descripción de la iniciativa:')),
                ('beneficiarios', models.TextField(blank=True, null=True, verbose_name='4. Beneficiarios:')),
                ('poblacion', models.TextField(blank=True, null=True, verbose_name='5.1. Cantidad Poblacion objetivo:')),
                ('poblacion_objetivo', models.TextField(blank=True, null=True, verbose_name='5.2. Caracterización Población objetivo (Urbana, rural, con enfoque diferencial, ciclo vida:')),
                ('valor_estimado', models.TextField(blank=True, null=True, verbose_name='6. Valor estimado de la Iniciativa')),
                ('descripcion_presupuesto', models.TextField(blank=True, null=True, verbose_name='6.1. Breve descripcioón del presupuesto estimado por actividades:')),
                ('ejecucion', models.TextField(blank=True, null=True, verbose_name='7. Tiempo de Ejecución en meses:')),
                ('lineas', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Formación', 'Formación'), ('Investigación e información', 'Investigación e información'), ('Creación y Producción', 'Creación y Producción'), ('Circulación y produccin', 'Circulación y produccin'), ('Circulación y apropiación', 'Circulación y apropiación'), ('Emprendimiento y asociatividad', 'Emprendimiento y asociatividad')], max_length=82, null=True, verbose_name='8. Líneas Estratégicas: ')),
                ('area', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Formación', 'Formación'), ('Investigación e información', 'Investigación e información'), ('Creación y Producción', 'Creación y Producción'), ('Circulación y produccin', 'Circulación y produccin'), ('Circulación y apropiación', 'Circulación y apropiación'), ('Emprendimiento y asociatividad', 'Emprendimiento y asociatividad')], max_length=82, null=True, verbose_name='9. Área (s) Artísticas + Patrimonio + Red de bibliotecas: ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meta1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta1', to='formularios.meta', verbose_name='Meta: *')),
                ('meta2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta2', to='formularios.meta', verbose_name='Meta: *')),
                ('meta3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta3', to='formularios.meta', verbose_name='Meta: *')),
                ('meta4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta4', to='formularios.meta', verbose_name='Meta: *')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formularios.perfil', verbose_name='Perfil: *')),
            ],
            options={
                'verbose_name': 'Formulario Hagamos Grande el Meta',
                'verbose_name_plural': 'Formulario Hagamos grande el Meta',
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del COmponente')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'COmponente',
                'verbose_name_plural': 'Componente',
            },
        ),
    ]
