# Generated by Django 3.2 on 2021-08-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20210722_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del país')),
                ('phone_code', models.CharField(max_length=5, verbose_name='Código número telefónico')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Modalidad')),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidad',
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Propuesta')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuesta',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='1.Correo electrónico')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='2.Nombres y apellidos')),
                ('agrupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='3.Nombre de la agrupación (si aplica)')),
                ('seudonimo', models.CharField(blank=True, max_length=100, null=True, verbose_name='4. Seudónimo (si aplica)')),
                ('identification', models.CharField(blank=True, max_length=30, null=True, verbose_name='5. Número de Identificación')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='País')),
                ('region', models.CharField(blank=True, max_length=30, null=True, verbose_name='Departamento')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Municipio')),
                ('adress', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.3. DIRECCIÓN DE VIVIENDA')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.5. TELÉFONO')),
                ('phone_movil', models.CharField(blank=True, max_length=30, null=True, verbose_name='2.6. CELULAR ')),
                ('obra1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Obra1 ')),
                ('obra2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Obra2 ')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pqrsd/file', verbose_name='Archivo adjunto')),
                ('archivo1', models.FileField(blank=True, null=True, upload_to='pqrsd/file', verbose_name='Archivo adjunto')),
                ('archivo2', models.FileField(blank=True, null=True, upload_to='pqrsd/file', verbose_name='Archivo adjunto')),
                ('archivo3', models.FileField(blank=True, null=True, upload_to='pqrsd/file', verbose_name=' Archivo adjunto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formularios.modalidad', verbose_name='Modalidad')),
                ('propuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formularios.propuesta', verbose_name='Propuesta')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formularios.typedocument', verbose_name='5.Tipo de documento')),
            ],
            options={
                'verbose_name': 'Informe PQRSD',
                'verbose_name_plural': 'Informe PQRSD',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del departamento')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre municipio')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.region', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
    ]
