# Generated by Django 3.2 on 2021-09-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_componente_meta_perfil_presupuesto_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='beneficiarios',
            field=models.TextField(blank=True, null=True, verbose_name='5. Beneficiarios:'),
        ),
    ]
