# Generated by Django 3.2 on 2021-09-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_alter_presupuesto_beneficiarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='codigo',
            field=models.CharField(default=11, max_length=254, verbose_name='codigo'),
            preserve_default=False,
        ),
    ]
