# Generated by Django 3.2 on 2021-08-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_city_country_modalidad_propuesta_region_torneo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneo',
            options={'verbose_name': 'Torneo del joropo', 'verbose_name_plural': 'Torneo del joropo'},
        ),
        migrations.AddField(
            model_name='torneo',
            name='archivo4',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', verbose_name='Los participantes de las modalidades de Golpe Inédito, Pasaje Inédito, Poema Inédito, deberán enviar una (1) copia del texto de la obra, escrita en computador en letra Arial 12, marcada y firmada únicamente con el seudónimo del compositor. Adjuntar el documento en un solo PDF.  '),
        ),
        migrations.AddField(
            model_name='torneo',
            name='expedicion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Lugar de Expedición: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='adress',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dirección residencia:'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='agrupacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la agrupación (si aplica):'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', verbose_name='Seleccione una foto artística haciendo clic en agregar archivo - Por favor ADJUNTE una fotografía artística digital ya sea a color o blanco y negro tamaño mínimo 800 x 600 Pixeles en una resolución mínima de 200 dpi.'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='archivo1',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', verbose_name='Cargar el Formulario N°1 - Inscripción al 53° Torneo Internacional del Joropo "MIGUEL ÁNGEL MARTÍN" totalmente diligenciado con los siguientes documentos: Fotocopias de la Cédula ciudadanía, extranjería y/o pasaporte del representante y de los integrantes según sea la modalidad y la certificación de residencia de mínimo 3 años emitida por la Alcaldía del municipio respectivo, o las juntas de acción comunal. (aplica solo para los participantes que se presenten por el departamento del Meta). Lo anterior se Adjunta en un solo archivo en formato PDF. *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='archivo2',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', verbose_name='Adjuntar el audio formato punto wav, mp3 etc... y vídeo y/o videos (mínimo una cámara máximo tres cámaras grabando simultáneamente) FHD, 1080p o superior de la propuesta según sea la modalidad seleccionada: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='archivo3',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', verbose_name=' Los participantes de las modalidades de Conjunto de Música Tradicional llanera y/o Ensambles Nuevos Formatos deberán enviar una breve, pero sólida justificación escrita de su obra, que incluya: Datos de la obra (forma y estilo), intención y/o concepto musical desarrollado y argumentar el ¿Porqué? del repertorio seleccionado. Esta podrá ser utilizada para presentar la obra ante el público por redes y medios de comunicación. Adjuntar el documento en un solo PDF. '),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='País de residencia: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='Correo *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='identification',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de identificación: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='modalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formularios.modalidad', verbose_name='Modalidad en la que participará: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres y Aepllidos del integrante de la agrupación que hará las veces de representante (si aplica) y/0 participante: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='obra1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Escriba el nombre de la obra N°1 y/o arreglo que presentará al concurso según lo solicitado en las bases: (No Aplica para las modalidades de, Pareja de Baile y Copleros). '),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='obra2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Escriba el nombre de la obra N°2 y/o arreglo que presentará al concurso según lo solicitado en las bases: (No Aplica para las modalidades de, Pareja de Baile y Copleros).'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono fijo:'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='phone_movil',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono celular: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='propuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formularios.propuesta', verbose_name='Propuesta: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ciudad de residencia: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='seudonimo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seudónimo (si aplica):'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='type_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formularios.typedocument', verbose_name='Tipo de identificación: *'),
        ),
    ]
