# Generated by Django 3.2 on 2021-09-13 05:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_meta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MÚSICA', 'MÚSICA'), ('DANZA', 'DANZA'), ('TEATRO', 'TEATRO'), ('CIRCO', 'CIRCO'), ('ARTES PLÁSTICAS Y VISUALES', 'ARTES PLÁSTICAS Y VISUALES'), ('CINEMATOGRAFÍA', 'CINEMATOGRAFÍA'), ('GASTRONIMÍA', 'GASTRONOMÍA'), ('LITERATURA', 'LITERATURA'), ('PATRIMONIO', 'PATRIMONIO'), ('RED DE BIBLIOTECAS PÚBLICAS DEL META', 'RED DE BIBLIOTECAS PÚBLICAS DEL META')], max_length=82, null=True, verbose_name='9. Área (s) Artísticas + Patrimonio + Red de bibliotecas: '),
        ),
    ]
