# Generated by Django 3.2 on 2021-08-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_auto_20210809_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Propuesta'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección residencia:'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País de residencia: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True, verbose_name='Correo *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='expedicion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Expedición: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='identification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de identificación: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='obra1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Escriba el nombre de la obra N°1 y/o arreglo que presentará al concurso según lo solicitado en las bases: (No Aplica para las modalidades de, Pareja de Baile y Copleros). '),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='obra2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Escriba el nombre de la obra N°2 y/o arreglo que presentará al concurso según lo solicitado en las bases: (No Aplica para las modalidades de, Pareja de Baile y Copleros).'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono fijo:'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='phone_movil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono celular: *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de residencia: *'),
        ),
    ]
