# Generated by Django 3.2 on 2021-08-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_auto_20210809_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='agrupacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la agrupación (si aplica)'),
        ),
    ]
