# Generated by Django 3.2 on 2021-09-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_alter_meta_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.componente', verbose_name='COmponente'),
        ),
    ]
