# Generated by Django 3.2 on 2021-08-21 19:12

from django.db import migrations, models
import formularios.models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_auto_20210821_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='archivo3',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', validators=[formularios.models.validate_file_size], verbose_name=' Los participantes de las modalidades de Conjunto de Música Tradicional llanera y/o Ensambles Nuevos Formatos deberán enviar una breve, pero sólida justificación escrita de su obra, que incluya: Datos de la obra (forma y estilo), intención y/o concepto musical desarrollado y argumentar el ¿Porqué? del repertorio seleccionado. Esta podrá ser utilizada para presentar la obra ante el público por redes y medios de comunicación. Adjuntar el documento en un solo PDF. '),
        ),
    ]
