# Generated by Django 3.2 on 2021-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_alter_meta_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='11. Observaciones:'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='ejecucion',
            field=models.IntegerField(blank=True, null=True, verbose_name='7. Tiempo de Ejecución en meses:'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='phone',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Teléfono fijo:'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='valor_estimado',
            field=models.IntegerField(blank=True, null=True, verbose_name='6. Valor estimado de la Iniciativa'),
        ),
    ]
