# Generated by Django 3.2 on 2021-08-22 01:58

from django.db import migrations, models
import formularios.models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_auto_20210821_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', validators=[formularios.models.file_size], verbose_name='Seleccione una foto artística haciendo clic en agregar archivo - Por favor ADJUNTE una fotografía artística digital ya sea a color o blanco y negro tamaño mínimo 800 x 600 Pixeles en una resolución mínima de 200 dpi.'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='archivo1',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', validators=[formularios.models.file_size], verbose_name='Cargar el Formulario N°1 - Inscripción al 53° Torneo Internacional del Joropo "MIGUEL ÁNGEL MARTÍN" totalmente diligenciado con los siguientes documentos: Fotocopias de la Cédula ciudadanía, extranjería y/o pasaporte del representante y de los integrantes según sea la modalidad y la certificación de residencia de mínimo 3 años emitida por la Alcaldía del municipio respectivo, o las juntas de acción comunal. (aplica solo para los participantes que se presenten por el departamento del Meta). Lo anterior se Adjunta en un solo archivo en formato PDF. *'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='archivo2',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', validators=[formularios.models.file_size], verbose_name='sdsd'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='archivo3',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', validators=[formularios.models.file_size], verbose_name=' Los participantes de las modalidades de Conjunto de Música Tradicional llanera y/o Ensambles Nuevos Formatos deberán enviar una breve, pero sólida justificación escrita de su obra, que incluya: Datos de la obra (forma y estilo), intención y/o concepto musical desarrollado y argumentar el ¿Porqué? del repertorio seleccionado. Esta podrá ser utilizada para presentar la obra ante el público por redes y medios de comunicación. Adjuntar el documento en un solo PDF. '),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='archivo4',
            field=models.FileField(blank=True, null=True, upload_to='torneo/file', validators=[formularios.models.file_size], verbose_name='Los participantes de las modalidades de Golpe Inédito, Pasaje Inédito, Poema Inédito, deberán enviar una (1) copia del texto de la obra, escrita en computador en letra Arial 12, marcada y firmada únicamente con el seudónimo del compositor. Adjuntar el documento en un solo PDF.  '),
        ),
    ]
