# Generated by Django 3.2 on 2021-09-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_auto_20210917_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filarmonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('considera', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Considera usted pertinente la creación de una orquesta filarmonica en el departamento del Meta:')),
                ('justifique', models.TextField(blank=True, null=True, verbose_name='Justifique su respuesta')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres y Aepllidos : *')),
                ('dirige', models.TextField(blank=True, null=True, verbose_name='Programa qu dirige')),
                ('grado', models.TextField(blank=True, null=True, verbose_name='Maximo grado en musica que haya cursado')),
                ('grupo', models.TextField(blank=True, null=True, verbose_name='Grupo que maneja actualmente en el municipio')),
                ('email', models.EmailField(blank=True, max_length=20, null=True, verbose_name='Correo *')),
                ('phone', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Teléfono fijo:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.city', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'FILARMONICA',
                'verbose_name_plural': 'FILARMONICA',
            },
        ),
    ]
