# Generated by Django 3.2 on 2021-09-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_auto_20210921_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formularios.city', verbose_name='Municipio'),
        ),
    ]
