# Generated by Django 3.2 on 2021-09-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0013_alter_presupuesto_lineas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='meta1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta1', to='formularios.meta', verbose_name='10. Seleccione Meta que articula con la iniciativa'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='meta2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta2', to='formularios.meta', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='meta3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta3', to='formularios.meta', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='meta4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta4', to='formularios.meta', verbose_name=''),
        ),
    ]
