# Generated by Django 3.2 on 2021-09-23 14:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0014_auto_20210923_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='lineas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Formación', 'Formación'), ('Investigación e información', 'Investigación e información'), ('Creación y Producción', 'Creación y Producción'), ('Circulación y producción', 'Circulación y producción'), ('Circulación y apropiación', 'Circulación y apropiación'), ('Emprendimiento y asociatividad', 'Emprendimiento y asociatividad')], max_length=82, null=True, verbose_name='8. Líneas Estratégicas: '),
        ),
    ]
