# Generated by Django 3.2.4 on 2021-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0015_alter_presupuesto_lineas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filarmonica',
            name='considera',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Considera usted pertinente la creación de una orquesta filarmónica en el departamento del Meta:'),
        ),
    ]
