# Generated by Django 3.2.4 on 2021-11-30 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formularios', '0016_alter_filarmonica_considera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apeliidos')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo contrato')),
                ('justifique', models.TextField(blank=True, null=True, verbose_name='Justifique su trabajo')),
                ('objeto', models.TextField(blank=True, null=True, verbose_name='Objeto del contrato')),
                ('email', models.EmailField(blank=True, max_length=20, null=True, verbose_name='Correo *')),
                ('phone', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Teléfono fijo:')),
                ('document', models.FileField(blank=True, null=True, upload_to='document/contratista', verbose_name='Documento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creador de actividad')),
            ],
            options={
                'verbose_name': 'FILARMONICA',
                'verbose_name_plural': 'FILARMONICA',
            },
        ),
    ]
