# Generated by Django 3.2.4 on 2021-11-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0017_contratista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratista',
            options={'verbose_name': 'CONTRATISTA', 'verbose_name_plural': 'CONTRATISTA'},
        ),
        migrations.AddField(
            model_name='contratista',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Area de trabajo(ejemplo musica)'),
        ),
        migrations.AddField(
            model_name='contratista',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo del trabajo'),
        ),
    ]
