# Generated by Django 3.2.4 on 2021-11-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0018_auto_20211130_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='cedula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula'),
        ),
    ]
