# Generated by Django 3.2.4 on 2021-11-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0019_contratista_cedula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratista',
            options={'verbose_name': 'DOCUMENTOS PATRIMONIO', 'verbose_name_plural': 'DOCUMENTOS PATRIMONIO'},
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='area',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='objeto',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='user',
        ),
        migrations.AlterField(
            model_name='contratista',
            name='justifique',
            field=models.TextField(blank=True, null=True, verbose_name='Justifique el documento'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo del Documento'),
        ),
    ]
