# Generated by Django 3.2.4 on 2022-06-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0021_asistencia_patrimonio_ruta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patrimonio',
            options={'verbose_name': 'Catalogo Patrimonio', 'verbose_name_plural': 'Catalogo patrimonio'},
        ),
    ]
