# Generated by Django 3.2.4 on 2022-06-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0022_alter_patrimonio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='Tiempoenvehiculo',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Tiempo en vehiculo'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='breve',
            field=models.TextField(blank=True, null=True, verbose_name='Breve Descripción'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='duracion',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='edad',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Edad recomendada'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='longitud',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='temporada',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Temporada'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tiempoapie',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Tiempo a pie'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Título'),
        ),
    ]
